#!/usr/bin/env sh

set -e
# set -x

SRC_DIR=$DYD_STEM

# echo "dev-shell"

DEST_DIR=$1
DEST_MAIN=$DEST_DIR/dyd/main

# copy assets to build
cp -s $SRC_DIR/dyd/assets/main $DEST_MAIN
cp -s -R $SRC_DIR/dyd/assets/traits/* $DEST_DIR/dyd/traits/

# copy version from root to build
# cp -s -R $SRC_DIR/dyd/traits/version $DEST_DIR/dyd/traits/

# add dependencies

# link the version of dryad that's needed for the current os/arch
DRYAD_VERSION="dryad-$DYD_OS-$DYD_ARCH"
DRYAD_DEP_PATH="$SRC_DIR/dyd/stems/native"
ln -s $DRYAD_DEP_PATH $DEST_DIR/dyd/stems/dryad





