#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''

# import assertion functions
. $SRC_DIR/dyd/assets/assertions.sh

_setup() {
	#
	# make a temporary working directory
	# this command is linux / osx agnostic
	# https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
	# echo "\[INFO\] creating temporary working directory" 1>&2;
	TEMP_DIR=''
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {
	# echo "[INFO] creating garden" 1>&2;

	mkdir -p "$TEMP_DIR/dyd/roots/root-01/dyd/assets"

	printf 'garden' > "$TEMP_DIR/dyd/type"
	printf 'root' > "$TEMP_DIR/dyd/roots/root-01/dyd/type"
	printf 'test-file-01' > "$TEMP_DIR/dyd/roots/root-01/dyd/assets/test-file-01"

	if [ -e "$TEMP_DIR/dyd/sprouts" ]; then
		echo "[ERROR] Fail: expected sprouts directory to be missing before wipe" 1>&2
		return 1
	fi

	:;
}

_test() {
	( \
	cd "$TEMP_DIR" && \
	dryad sprouts wipe --log-level="$DYD_LOG_LEVEL" \
	) 1>&2;
}

_verify() {
	assert_directory_exists "$TEMP_DIR/dyd"
	assert_file_content_equals "$TEMP_DIR/dyd/type" "garden"

	assert_directory_exists "$TEMP_DIR/dyd/sprouts"
	SPROUTS_MODE=$(ls -ld "$TEMP_DIR/dyd/sprouts" | sed 's/ .*//')
	case "$SPROUTS_MODE" in
		??w*)
			echo "[ERROR] Fail: expected newly created sprouts directory owner write bit to be unset after wipe" 1>&2
			return 1
			;;
	esac

	assert_file_content_equals "$TEMP_DIR/dyd/roots/root-01/dyd/type" "root"
	assert_file_content_equals "$TEMP_DIR/dyd/roots/root-01/dyd/assets/test-file-01" "test-file-01"
	SPROUTS_FIRST_CHILD=$(find "$TEMP_DIR/dyd/sprouts" -mindepth 1 -maxdepth 1 -print -quit)
	if [ -n "$SPROUTS_FIRST_CHILD" ]; then
		echo "[ERROR] Fail: expected sprouts directory to be empty after wipe" 1>&2
		return 1
	fi
	:;
}

_teardown() {
	# echo "\[INFO\] tearing down fixtures" 1>&2;
	if [ -d "$TEMP_DIR" ]; then
		chmod -R 755 "$TEMP_DIR"
		rm -rf "$TEMP_DIR"
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
