#!/usr/bin/env bash
set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''

. $SRC_DIR/dyd/assets/assertions.sh

_setup() {
	TEMP_DIR=''
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {
	cp -R "$SRC_DIR/dyd/assets/sample-garden/." "$TEMP_DIR"
	chmod -R 755 "$TEMP_DIR"
}

_test() {
	EDITOR_PATH="$TEMP_DIR/dyd/roots/root-01/dyd/commands/dev-editor"
	OUTPUT_FILE="$TEMP_DIR/dyd/heap/root-develop-15/output"
	mkdir -p "$TEMP_DIR/dyd/heap/root-develop-15"
	script -q /dev/null -c "cd \"$TEMP_DIR\" && dryad root develop start dyd/roots/root-01 --editor=\"$EDITOR_PATH\" --log-level=\"$DYD_LOG_LEVEL\"" < /dev/null 2> "$OUTPUT_FILE" 1>&2
}

_verify() {
	assert_file_content_equals "$TEMP_DIR/dyd/roots/root-01/dyd/assets/keep.txt" "keep"
	assert_file_not_exists "$TEMP_DIR/dyd/roots/root-01/dyd/assets/new.txt"

	if ! grep -q "warning: root develop exited with unsaved changes; snapshot " "$OUTPUT_FILE"; then
		echo "[ERROR] Fail: expected warning about unsaved changes" 1>&2
		return 1
	fi
}

_teardown() {
	if [ -d "$TEMP_DIR" ]; then
		chmod -R 755 "$TEMP_DIR"
		rm -rf "$TEMP_DIR"
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
