#!/usr/bin/env sh

set -e
# set -x

SRC_DIR=$(pwd)

# echo "dryad"

DEST_DIR=$1
DEST_MAIN=$DEST_DIR/dyd/main

# copy assets to build
echo -n "$DYD_OS" > $DEST_DIR/dyd/traits/os
echo -n "$DYD_ARCH" > $DEST_DIR/dyd/traits/arch

# run go build for specified arch
# diable workspace mode to avoid "missing module" errors
cd $SRC_DIR/dyd/stems/src/dyd/assets/ && \
GOARCH="$DYD_ARCH" \
GOOS="$DYD_OS" \
GOWORK=off \
go build -ldflags '-s -w' -o $DEST_MAIN