#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD

if [ -d "$SRC_DIR/dyd/assets" ]; then
	cp -R "$SRC_DIR/dyd/assets/." "$DEST_DIR/dyd/assets/"
else
	mkdir -p "$DEST_DIR/dyd/assets"
fi

mkdir -p "$DEST_DIR/dyd/traits"
printf "stable" > "$DEST_DIR/dyd/traits/channel"
