#!/usr/bin/env bash

#
# turn this on to debug script
set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

SRC_DIR=$DYD_STEM
DEST_DIR="$1"

SYSTEM="$DYD_OS-$DYD_ARCH"

case "$SYSTEM" in
	'darwin-amd64' )
		BUILD='https://go.dev/dl/go1.23.5.darwin-amd64.tar.gz'
		;;
	'darwin-arm64' )
		BUILD='https://go.dev/dl/go1.23.5.darwin-arm64.tar.gz'
		;;
	'linux-amd64' )
		BUILD='https://go.dev/dl/go1.23.5.linux-amd64.tar.gz'
		;;
	'linux-arm64' )
		BUILD='https://go.dev/dl/go1.23.5.linux-arm64.tar.gz'
		;;
	* )
		echo "unsupported system $SYSTEM"
		exit 1
		::
esac

printf %s "go" > "$DEST_DIR/dyd/traits/name"
printf %s "$BUILD" > "$DEST_DIR/dyd/traits/source"

# download the binary as the main
TEMP_DIR=$(mktemp -d)

curl -L "$BUILD" -o "$TEMP_DIR/go.tar"

mkdir -p $DEST_DIR/dyd/assets
tar -xf $TEMP_DIR/go.tar -C $DEST_DIR/dyd/assets
rm -rf $TEMP_DIR

cat $SRC_DIR/dyd/assets/main > $DEST_DIR/dyd/commands/default