#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

SRC_DIR=$DYD_STEM
DEST_DIR="$1"

OS="$(cat "$SRC_DIR/dyd/traits/os")"
ARCH="$(cat "$SRC_DIR/dyd/traits/arch")"
SYSTEM="$OS-$ARCH"

SOURCE_FILE="$SRC_DIR/dyd/assets/$SYSTEM.source"
if [ ! -f "$SOURCE_FILE" ]; then
	echo "unsupported system $SYSTEM"
	exit 1
fi

BUILD="$(cat "$SOURCE_FILE")"
if [ -z "$BUILD" ]; then
	echo "unsupported system $SYSTEM"
	exit 1
fi

printf %s "go" > "$DEST_DIR/dyd/traits/name"
printf %s "$BUILD" > "$DEST_DIR/dyd/traits/source"

# download the binary as the main
TEMP_DIR=$(mktemp -d)

curl -L "$BUILD" -o "$TEMP_DIR/go.tar"

mkdir -p $DEST_DIR/dyd/assets
tar -xf $TEMP_DIR/go.tar -C $DEST_DIR/dyd/assets
rm -rf $TEMP_DIR

cat $SRC_DIR/dyd/assets/main > $DEST_DIR/dyd/commands/dyd-stem-run
