#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''
TEST_OUTPUT=''
EXPECTED_OUTPUT='dev - development
docs - documentation
prod - production'

# import assertion functions
. $SRC_DIR/dyd/assets/assertions.sh

_setup() {
	#
	# make a temporary working directory
	# this command is linux / osx agnostic
	# https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
	# echo "\[INFO\] creating temporary working directory" 1>&2;
	TEMP_DIR=''
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {

	# copy the sample garden to the working directory
	cp -R "$SRC_DIR/dyd/assets/sample-garden/." "$TEMP_DIR"
	chmod -R 755 "$TEMP_DIR"

	cd "$TEMP_DIR"
	:;
}

_test() {

	TEST_OUTPUT=$(dryad scopes list | sort);
}

_verify() {
	if [ "$TEST_OUTPUT" != "$EXPECTED_OUTPUT" ]; then
		echo "[ERROR] Fail: scopes list output did not match. expected ($EXPECTED_OUTPUT), got ($TEST_OUTPUT)" 1>&2
		return 1
	fi
	:;
}

_teardown() {
	# echo "\[INFO\] tearing down fixtures" 1>&2;
	if [ -d "$TEMP_DIR" ]; then
		rm -rf $TEMP_DIR
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
