#!/usr/bin/env bash

set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''

. "$SRC_DIR/dyd/assets/assertions.sh"

_setup() {
	TEMP_DIR=''
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {
	cp -R "$SRC_DIR/dyd/assets/sample-garden/." "$TEMP_DIR"
	chmod -R 755 "$TEMP_DIR"
	cd "$TEMP_DIR"
}

_test() {
	dryad root replace dyd/roots/root-01 dyd/roots/root-02 --log-level="$DYD_LOG_LEVEL" 1>&2
	dryad roots build --log-level="$DYD_LOG_LEVEL" 1>&2
}

_verify() {
	assert_directory_exists "$TEMP_DIR/dyd"
	assert_file_content_equals "$TEMP_DIR/dyd/type" "garden"

	assert_directory_exists "$TEMP_DIR/dyd/roots/root-01"
	assert_directory_exists "$TEMP_DIR/dyd/roots/root-02"

	# Ensure replace preserves target variant selector when rewriting dependents.
	assert_file_content_equals "$TEMP_DIR/dyd/roots/root-03/dyd/requirements/root-01" "root:../../../root-02?arch=amd64&os=linux"

	assert_directory_exists "$TEMP_DIR/dyd/sprouts/root-03"
	assert_file_content_equals "$TEMP_DIR/dyd/sprouts/root-03/dyd/type" "sprout"
}

_teardown() {
	if [ -d "$TEMP_DIR" ]; then
		chmod -R 755 "$TEMP_DIR"
		rm -rf "$TEMP_DIR"
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
