#!/usr/bin/env sh

set -e
# set -x

SRC_DIR=$(pwd)

# echo "dev-shell"

DEST_DIR=$1
DEST_MAIN=$DEST_DIR/dyd/main

# copy assets to build
cp --symbolic-link $SRC_DIR/dyd/assets/main $DEST_MAIN
cp --symbolic-link -R $SRC_DIR/dyd/assets/traits/* $DEST_DIR/dyd/traits/

# copy version from root to build
# cp --symbolic-link -R $SRC_DIR/dyd/traits/version $DEST_DIR/dyd/traits/

# add tools as dependencies
ln -s $SRC_DIR/dyd/stems/gpg-package-sign $DEST_DIR/dyd/stems/gpg-package-sign
ln -s $SRC_DIR/dyd/stems/gpg-package-verify $DEST_DIR/dyd/stems/gpg-package-verify

# ls -al $DEST_DIR/dyd/traits