#!/usr/bin/env bash
set -euf -o pipefail

printf "workspace\n" > "$DYD_STEM/dyd/assets/file.txt"

ROOT_PATH="$DYD_GARDEN/dyd/roots/root-01/dyd/assets/file.txt"
printf "external\n" > "$ROOT_PATH"

set +e
"$DYD_CLI_BIN" root develop-save
STATUS=$?
set -e

if [ $STATUS -eq 0 ]; then
  echo "[ERROR] Fail: expected develop-save to fail on conflict" 1>&2
  exit 1
fi

exit 0
