#!/usr/bin/env sh

set -e

echo "signing test package"

SRC_DIR=$(pwd)

# ls -al $SRC_DIR/dyd/stems

# which ls
# which cat
# which cp
# which dryad

DEST_DIR=$1
DEST_MAIN=$DEST_DIR/dyd/main


cat $SRC_DIR/dyd/fingerprint
echo ""

cp -r --symbolic-link $SRC_DIR/dyd/stems/base/* $DEST_DIR/

PACKAGE_DIR="$DEST_DIR" \
GPG_KEY_ID="$TEST_KEY_ID" \
GPG_KEY_PUB="$TEST_KEY_PUB" \
GPG_KEY_PRIV="$TEST_KEY_PRIV" \
GPG_KEY_PASS="$TEST_KEY_PASS" \
GPG_KEY_FAKE_TIME="$TEST_KEY_FAKE_TIME" \
	gpg-package-sign

# echo "$TEST_KEY_PUB" | gpg --import
# echo "$TEST_KEY_PRIV" | gpg --import --allow-secret-key-import
# echo "$TEST_KEY_PASS" | gpg --sign \
# 	--batch \
# 	--yes \
# 	--passphrase-fd 0 \
# 	-u $TEST_KEY_ID \
# 	--armor \
# 	--output $DEST_DIR/dyd/traits/signature \
# 	$DEST_DIR/dyd/fingerprint

# DEST_DIR="$DEST_DIR" sh -i


