#!/usr/bin/env bash
set -euf -o pipefail

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD

cp -R "$SRC_DIR/dyd/assets/commands/." "$DEST_DIR/dyd/commands/"
ln -s "$SRC_DIR/dyd/dependencies/dryad" "$DEST_DIR/dyd/dependencies/dryad"
ln -s "$SRC_DIR/dyd/dependencies/http-server" "$DEST_DIR/dyd/dependencies/http-server"
