#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

OUT_DIR="$DYD_GARDEN/dyd/heap/run-04"
mkdir -p "$OUT_DIR"

printf "dev\n" > "$OUT_DIR/which"
