#!/usr/bin/env sh

set -e
# set -x

SRC_DIR=$(pwd)

echo "test-package:base"

# ls -al $SRC_DIR/dyd/stems

# which ls
# which cat
# which cp
# which dryad

DEST_DIR=$1
DEST_MAIN=$DEST_DIR/dyd/main

cp --symbolic-link $SRC_DIR/dyd/assets/main $DEST_MAIN

ln -s $SRC_DIR/dyd/stems/echo $DEST_DIR/dyd/stems/echo

echo "test-package" > $DEST_DIR/dyd/traits/name
echo "socks" > $DEST_DIR/dyd/traits/author

ls -al $DEST_DIR/dyd/traits