#!/usr/bin/env bash
set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''

. "$SRC_DIR/dyd/assets/assertions.sh"

_setup() {
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {
	cp -R "$SRC_DIR/dyd/assets/sample-garden/." "$TEMP_DIR"
	chmod -R 755 "$TEMP_DIR"
	cd "$TEMP_DIR"
}

_test() {
	dryad root build "dyd/roots/root-parent" --log-level="$DYD_LOG_LEVEL" > /dev/null
}

_verify() {
	variant_stem="$TEMP_DIR/dyd/sprouts/root-variant/dyd/dependencies/stem"
	assert_file_exists "$variant_stem/dyd/traits/os"
	assert_file_content_equals "$variant_stem/dyd/traits/os" "linux"
	assert_directory_not_exists "$variant_stem/dyd/traits/variants"
}

_teardown() {
	if [ -d "$TEMP_DIR" ]; then
		chmod -R 755 "$TEMP_DIR"
		rm -rf "$TEMP_DIR"
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
