#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

printf "STDOUT-OK\n"
printf "STDERR-OK\n" 1>&2

OUT_DIR="$DYD_GARDEN/dyd/heap/sprout-run-02--supports-executables-and-log--executes-a-scoped-script"
mkdir -p "$OUT_DIR"
printf "main\n" > "$OUT_DIR/which"
