#!/usr/bin/env bash
set -euf -o pipefail

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD

mkdir -p "$DEST_DIR/dyd/assets"
if [ -f "$SRC_DIR/dyd/secrets/value.txt" ]; then
  cp "$SRC_DIR/dyd/secrets/value.txt" "$DEST_DIR/dyd/assets/value.txt"
else
  printf 'missing' > "$DEST_DIR/dyd/assets/value.txt"
fi
