#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''
FINGERPRINT_BEFORE=''
FINGERPRINT_AFTER=''

# import assertion functions
. $SRC_DIR/dyd/assets/assertions.sh

_setup() {
	#
	# make a temporary working directory
	# this command is linux / osx agnostic
	# https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
	# echo "\[INFO\] creating temporary working directory" 1>&2;
	TEMP_DIR=''
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {

	# echo "[INFO] creating garden" 1>&2;

	# copy the sample garden to the working directory
	cp -R "$SRC_DIR/dyd/assets/sample-garden/." "$TEMP_DIR" 
	chmod -R 755 "$TEMP_DIR"

	cd "$TEMP_DIR"
	:;
}

_test() {

	(dryad root build "dyd/roots/root-01" --log-level="$DYD_LOG_LEVEL") 1>&2;

	FINGERPRINT_BEFORE=$(cat "dyd/sprouts/root-01/dyd/fingerprint")
	if [ -z "$FINGERPRINT_BEFORE" ]; then
		echo "[ERROR] Fail: initial fingerprint should not be empty" 1>&2
		return 1
	fi

	printf "test-secret-01-updated" > "dyd/roots/root-01/dyd/secrets/test-secret-01"

	(dryad root build "dyd/roots/root-01" --log-level="$DYD_LOG_LEVEL") 1>&2;

	FINGERPRINT_AFTER=$(cat "dyd/sprouts/root-01/dyd/fingerprint")
	if [ -z "$FINGERPRINT_AFTER" ]; then
		echo "[ERROR] Fail: updated fingerprint should not be empty" 1>&2
		return 1
	fi
}

_verify() {
	assert_directory_exists "$TEMP_DIR/dyd"
	assert_file_content_equals "$TEMP_DIR/dyd/type" "garden"

	assert_directory_exists "$TEMP_DIR/dyd/sprouts/root-01"
	assert_file_content_equals "$TEMP_DIR/dyd/sprouts/root-01/dyd/type" "stem"

	assert_file_content_equals "$TEMP_DIR/dyd/sprouts/root-01/dyd/assets/test-file-01" "test-file-01"
	assert_directory_exists "$TEMP_DIR/dyd/sprouts/root-01/dyd/assets/test-dir-01"
	assert_file_content_equals "$TEMP_DIR/dyd/sprouts/root-01/dyd/assets/test-dir-01/test-file-02" "test-file-02"

	assert_directory_exists "$TEMP_DIR/dyd/sprouts/root-01/dyd/secrets/"
	assert_file_content_equals "$TEMP_DIR/dyd/sprouts/root-01/dyd/secrets/test-secret-01" "test-secret-01-updated"
	assert_directory_exists "$TEMP_DIR/dyd/sprouts/root-01/dyd/secrets/test-secret-02"
	assert_file_content_equals "$TEMP_DIR/dyd/sprouts/root-01/dyd/secrets/test-secret-02/test-secret-02" "test-secret-02"

	if [ "$FINGERPRINT_BEFORE" = "$FINGERPRINT_AFTER" ]; then
		echo "[ERROR] Fail: expected stem fingerprint to change after secrets update" 1>&2
		return 1
	fi

	:;
}

_teardown() {
	# echo "\[INFO\] tearing down fixtures" 1>&2;
	if [ -d "$TEMP_DIR" ]; then
		chmod -R 755 "$TEMP_DIR"
		rm -rf "$TEMP_DIR"
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
