#!/usr/bin/env bash
set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''

TEST_VARIANT_OUTPUT=''
TEST_TRAIT_OUTPUT=''
TEST_STDIN_OUTPUT=''
TEST_SPROUT_OUTPUT=''

. "$SRC_DIR/dyd/assets/assertions.sh"

_setup() {
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {
	cp -R "$SRC_DIR/dyd/assets/sample-garden/." "$TEMP_DIR"
	chmod -R 755 "$TEMP_DIR"
	TEMP_DIR="$(cd "$TEMP_DIR" && pwd -P)"
	cd "$TEMP_DIR"
}

_test() {
	TEST_VARIANT_OUTPUT=$(
		dryad roots list \
			--include='root.variant() == "arch=amd64+os=linux" || root.variant() == "os=darwin"' \
			| sort
	)

	TEST_TRAIT_OUTPUT=$(
		dryad roots list \
			--include='root.trait("value.txt") == "linux"' \
			| sort
	)

	TEST_STDIN_OUTPUT=$(
		printf '%s\n%s\n' \
			'dyd/roots/root-implicit-any?arch=amd64&os=linux' \
			'dyd/roots/root-option-list?os=darwin' \
			| dryad roots list --from-stdin \
			| sort
	)

	TEST_SPROUT_OUTPUT=$(
		printf '%s\n' 'dyd/roots/root-option-list?os=darwin' \
			| dryad roots list --from-stdin --to-sprouts
	)
}

_verify() {
	EXPECTED_VARIANT_OUTPUT=$'dyd/roots/root-implicit-any?arch=amd64&os=linux\ndyd/roots/root-option-list?os=darwin'
	EXPECTED_TRAIT_OUTPUT=$'dyd/roots/root-implicit-any?arch=amd64&os=linux\ndyd/roots/root-implicit-any?arch=arm64&os=linux\ndyd/roots/root-no-match?os=linux'
	EXPECTED_STDIN_OUTPUT=$'dyd/roots/root-implicit-any?arch=amd64&os=linux\ndyd/roots/root-option-list?os=darwin'
	EXPECTED_SPROUT_OUTPUT='dyd/sprouts/root-option-list?os=darwin'

	assert_all_equal "$TEST_VARIANT_OUTPUT" "$EXPECTED_VARIANT_OUTPUT"
	assert_all_equal "$TEST_TRAIT_OUTPUT" "$EXPECTED_TRAIT_OUTPUT"
	assert_all_equal "$TEST_STDIN_OUTPUT" "$EXPECTED_STDIN_OUTPUT"
	assert_all_equal "$TEST_SPROUT_OUTPUT" "$EXPECTED_SPROUT_OUTPUT"
}

_teardown() {
	if [ -d "$TEMP_DIR" ]; then
		chmod -R 755 "$TEMP_DIR"
		rm -rf "$TEMP_DIR"
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
