#!/usr/bin/env sh

set -eu

echo "[info] signing package $(cat $PACKAGE_DIR/dyd/fingerprint)"

echo "[info] preparing signature traits"

rm -rf $PACKAGE_DIR/dyd/traits/signature
mkdir -p $PACKAGE_DIR/dyd/traits/signature

echo -n "gpg" > $PACKAGE_DIR/dyd/traits/signature/type
echo -n "$GPG_KEY_ID" > $PACKAGE_DIR/dyd/traits/signature/author
echo -n "$GPG_KEY_PUB" > $PACKAGE_DIR/dyd/traits/signature/key
echo "[info] done"

echo "[info] generating content fingerprint"

CONTENT_FINGERPRINT=$(cd $PACKAGE_DIR && dryad stem fingerprint --exclude="^((dyd/traits/signature/signature)|(dyd/traits/signature/content-fingerprint)|(dyd/traits/root-fingerprint))$")
echo "[info] content fingerprint $CONTENT_FINGERPRINT"
echo -n "$CONTENT_FINGERPRINT" > $PACKAGE_DIR/dyd/traits/signature/content-fingerprint
echo "[info] done"

echo "[info] signing content fingerprint"

KEYRING=$(mktemp)
cleanup () {
	echo "[info] cleaning up"
	rm "$KEYRING"
	echo "[info] done"
}
trap cleanup EXIT

echo "$GPG_KEY_PUB" | gpg \
	--no-default-keyring \
	--keyring "$KEYRING" \
	--import \
	--quiet

echo "$GPG_KEY_PRIV" | gpg \
	--no-default-keyring \
	--keyring "$KEYRING" \
	--import \
	--allow-secret-key-import \
	--quiet

echo "$GPG_KEY_PASS" | gpg --sign \
	--no-default-keyring \
	--keyring "$KEYRING" \
	--trust-model always \
	--quiet \
	--pinentry-mode loopback \
	--yes \
	--passphrase-fd 0 \
	-u $GPG_KEY_ID \
	--armor \
	--detach-sig \
	--output $PACKAGE_DIR/dyd/traits/signature/signature \
	--faked-system-time $GPG_KEY_FAKE_TIME \
	$PACKAGE_DIR/dyd/traits/signature/content-fingerprint

echo "[info] done"

