#!/usr/bin/env sh

set -eu


echo "building sign-package"

SRC_DIR=$(pwd)
DEST_DIR=$1

cat $SRC_DIR/dyd/assets/main > $DEST_DIR/dyd/main

echo "sign-package" > $DEST_DIR/dyd/traits/name
echo "socks" > $DEST_DIR/dyd/traits/author

echo "done"