#!/usr/bin/env bash
set -euf -o pipefail

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD

mkdir -p "$DEST_DIR/dyd/assets"
if [ -d "$SRC_DIR/dyd/assets" ]; then
	cp -R "$SRC_DIR/dyd/assets/." "$DEST_DIR/dyd/assets/"
fi

mkdir -p "$DEST_DIR/dyd/dependencies"
if [ -d "$SRC_DIR/dyd/dependencies" ]; then
	for dep in "$SRC_DIR"/dyd/dependencies/*; do
		if [ ! -e "$dep" ]; then
			continue
		fi
		dep_name=$(basename "$dep")
		ln -s "$dep" "$DEST_DIR/dyd/dependencies/$dep_name"
	done
fi
