#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''

ROOTS=("root-01" "root-02" "root-03" "root-04" "root-05")
declare -A ROOT_PATHS

# import assertion functions
. $SRC_DIR/dyd/assets/assertions.sh

_setup() {
	#
	# make a temporary working directory
	# this command is linux / osx agnostic
	# https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
	# echo "\[INFO\] creating temporary working directory" 1>&2;
	TEMP_DIR=''
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {
	# echo "[INFO] creating garden" 1>&2;

	# copy the sample garden to the working directory
	cp -R "$SRC_DIR/dyd/assets/sample-garden/." "$TEMP_DIR" 
	chmod -R 755 "$TEMP_DIR"

	:;
}

_test() {
	cd "$TEMP_DIR/dyd/roots";
	for root_name in "${ROOTS[@]}"; do
		ROOT_PATHS["$root_name"]=$(dryad root path "$root_name" --log-level="$DYD_LOG_LEVEL");
	done
}

_verify() {
	# On osx systems, the base temp dir may be a symlink to another location.
	# dryad should handle this by resolving the symlink and returning the absolute path,
	# so in this test case we need to make sure that we do the same
	TEMP_DIR=$(readlink -f "$TEMP_DIR")

	for root_name in "${ROOTS[@]}"; do
		assert_all_equal "${ROOT_PATHS[$root_name]}" "$TEMP_DIR/dyd/roots/$root_name"
	done

	:;
}

_teardown() {
	# echo "\[INFO\] tearing down fixtures" 1>&2;
	if [ -d "$TEMP_DIR" ]; then
		chmod -R 755 "$TEMP_DIR"
		rm -rf "$TEMP_DIR"
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
