#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD

# import assertion functions
. $SRC_DIR/dyd/assets/assertions.sh

# write files to temp dir
for i1 in $(seq -w 1 10);
do
    mkdir -p "$DEST_DIR/dyd/assets/$i1"
    for i2 in $(seq -w 1 10);
    do
        mkdir -p "$DEST_DIR/dyd/assets/$i1/$i2"
        for i3 in $(seq -w 1 10);
        do
            printf '%s' "$i3" > "$DEST_DIR/dyd/assets/$i1/$i2/$i3"
        done
    done
done

# assert all files are there using a second pass
for i1 in $(seq -w 1 10);
do
    assert_directory_exists "$DEST_DIR/dyd/assets/$i1"
    for i2 in $(seq -w 1 10);
    do
        assert_directory_exists "$DEST_DIR/dyd/assets/$i1/$i2"
        for i3 in $(seq -w 1 10);
        do
            assert_file_content_equals "$DEST_DIR/dyd/assets/$i1/$i2/$i3" "$i3"
        done
    done
done
