#!/usr/bin/env sh

set -e

echo "adding secret"

SRC_DIR=$DYD_STEM
DEST_DIR=$1

# copying the secrets to the build stem
mkdir -p $DEST_DIR/dyd/secrets
cp --symbolic-link -R $SRC_DIR/dyd/secrets/* $DEST_DIR/dyd/secrets/
