#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

_SET_GLOBALS () {
	SRC_PACKAGE=$DYD_STEM
	DEST_PACKAGE=$1

	OS="$(cat "$SRC_PACKAGE/dyd/traits/os")"
	ARCH="$(cat "$SRC_PACKAGE/dyd/traits/arch")"
	VERSION="$(cat "$SRC_PACKAGE/dyd/traits/version")"
	PLATFORM="$OS-$ARCH"

	case $DYD_LOG_LEVEL in
		"debug" | "trace" )
			CURL_LOGS=""
			set -x
		;;
		* )
			CURL_LOGS="--silent"
		;;
	esac

}

_BUILD_PACKAGE () {
	SOURCE_FILE="$SRC_PACKAGE/dyd/assets/$VERSION/$PLATFORM.source"
	if [ ! -f "$SOURCE_FILE" ]; then
		echo "unsupported platform $PLATFORM for version $VERSION"
		exit 1
	fi

	BUILD="$(cat "$SOURCE_FILE")"

	if [ -z "$BUILD" ]; then
		echo "unsupported platform $PLATFORM for version $VERSION"
		exit 1
	fi

	printf %s "envsubst" > "$DEST_PACKAGE/dyd/traits/name"
	printf %s "$VERSION" > "$DEST_PACKAGE/dyd/traits/version"
	printf %s "$BUILD" > "$DEST_PACKAGE/dyd/traits/source"

	curl $CURL_LOGS -L "$BUILD" -o "$DEST_PACKAGE/dyd/commands/dyd-stem-run"

}

_SET_GLOBALS "$@"
_BUILD_PACKAGE
