#!/bin/sh
set -eu

if command -v open 2>&1 >/dev/null
then
    open "$DYD_GARDEN/dyd/sprouts/docs/dyd/assets/site/index.html"
elif command -v xdg-open 2>&1 >/dev/null
then
    xdg-open "$DYD_GARDEN/dyd/sprouts/docs/dyd/assets/site/index.html"
else
    exit 1
fi

