#!/usr/bin/env sh

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -eu

_setup_globals () {
    SRC_PACKAGE=$DYD_STEM

    DEST_PACKAGE=$DYD_BUILD
    DEST_MAIN=$DEST_PACKAGE/dyd/commands/dyd-stem-run
}

_setup_logging () {
    case $DYD_LOG_LEVEL in
        # turn on shell script debug logs for trace and debug log levels
        'debug' | 'trace' ) set -x ;;
        * ) ;;
    esac
}

_build_package () {
    # copy source code to stem assets
    cp -s -R $SRC_PACKAGE/dyd/assets/* $DEST_PACKAGE/dyd/assets/

    # copy traits to stem
    cp -s -R $SRC_PACKAGE/dyd/traits/* $DEST_PACKAGE/dyd/traits/

}

_setup_logging
_setup_globals
_build_package