#!/usr/bin/env bash
set -euf -o pipefail

rm -f "$DYD_STEM/dyd/assets/file.txt"

OUT_DIR="$DYD_GARDEN/dyd/heap/root-develop-status-03--deleted-file"
mkdir -p "$OUT_DIR"

"$DYD_CLI_BIN" root develop status > "$OUT_DIR/status"
