#!/usr/bin/env sh

set -e
# set -x

SRC_DIR=$DYD_STEM

# echo "dryad"

DEST_DIR=$1
DEST_MAIN=$DEST_DIR/dyd/main

OS="$(cat $SRC_DIR/dyd/traits/os)"
ARCH="$(cat $SRC_DIR/dyd/traits/arch)"

# copy assets to build
echo -n "$OS" > $DEST_DIR/dyd/traits/os
echo -n "$ARCH" > $DEST_DIR/dyd/traits/arch

# run go build for specified arch
# diable workspace mode to avoid "missing module" errors
cd $SRC_DIR/dyd/stems/src/dyd/assets/ && \
GOARCH="$ARCH" \
GOOS="$OS" \
GOWORK=off \
go build  -o $DEST_MAIN