#!/usr/bin/env sh

set -e
# set -x

SRC_DIR=$DYD_STEM

# echo "dryad"

DEST_DIR=$DYD_BUILD

# copy assets from builds to release

TEMP_DIR=$(mktemp -d)

VERSION="$(cat $SRC_DIR/dyd/dependencies/darwin-arm64/dyd/traits/version)"
cp -L $SRC_DIR/dyd/dependencies/darwin-arm64/dyd/commands/default $DEST_DIR/dyd/assets/dryad-$VERSION-darwin-arm64
chmod 0755 $DEST_DIR/dyd/assets/dryad-$VERSION-darwin-arm64

VERSION="$(cat $SRC_DIR/dyd/dependencies/darwin-amd64/dyd/traits/version)"
cp -L $SRC_DIR/dyd/dependencies/darwin-amd64/dyd/commands/default $DEST_DIR/dyd/assets/dryad-$VERSION-darwin-amd64
chmod 0755 $DEST_DIR/dyd/assets/dryad-$VERSION-darwin-amd64

VERSION="$(cat $SRC_DIR/dyd/dependencies/linux-arm64/dyd/traits/version)"
cp -L $SRC_DIR/dyd/dependencies/linux-arm64/dyd/commands/default $DEST_DIR/dyd/assets/dryad-$VERSION-linux-arm64
chmod 0755 $DEST_DIR/dyd/assets/dryad-$VERSION-linux-arm64

VERSION="$(cat $SRC_DIR/dyd/dependencies/linux-amd64/dyd/traits/version)"
cp -L $SRC_DIR/dyd/dependencies/linux-amd64/dyd/commands/default $DEST_DIR/dyd/assets/dryad-$VERSION-linux-amd64
chmod 0755 $DEST_DIR/dyd/assets/dryad-$VERSION-linux-amd64

VERSION="$(cat $SRC_DIR/dyd/dependencies/src/dyd/traits/version)"
cp -LR $SRC_DIR/dyd/dependencies/src/dyd/assets $TEMP_DIR/dryad
chmod -R 0755 $TEMP_DIR/dryad
tar -chzvf $DEST_DIR/dyd/assets/dryad-$VERSION-src.tar.gz -C $TEMP_DIR ./dryad

cp -LR $SRC_DIR/dyd/dependencies/bash_autocomplete/dyd/assets/dryad $DEST_DIR/dyd/assets/dryad-$VERSION-bash-autocomplete

cp -LR $SRC_DIR/dyd/dependencies/install-script/dyd/assets/install.sh $DEST_DIR/dyd/assets/dryad-$VERSION-install.sh

rm -rf $TEMP_DIR