#!/usr/bin/env sh

set -e
# set -x

SRC_DIR=$DYD_STEM

# echo "dryad"

DEST_DIR=$1
DEST_MAIN=$DEST_DIR/dyd/commands/default

OS="$DYD_OS"
ARCH="$DYD_ARCH"
VERSION="$(cat $SRC_DIR/dyd/stems/src/dyd/traits/version)"
FINGERPRINT="$(cat $SRC_DIR/dyd/stems/src/dyd/fingerprint)"

# copy assets to build
printf %s "$OS" > $DEST_DIR/dyd/traits/os
printf %s "$ARCH" > $DEST_DIR/dyd/traits/arch
printf %s "$VERSION" > $DEST_DIR/dyd/traits/version


# run go build for specified arch
# diable workspace mode to avoid "missing module" errors
cd $SRC_DIR/dyd/stems/src/dyd/assets/ && \
GOARCH="$ARCH" \
GOOS="$OS" \
GOWORK=off \
go build \
	-o $DEST_MAIN \
	-ldflags "-X=main.Version=$VERSION,-X=main.Fingerprint=$FINGERPRINT,-s,-w"
