#!/usr/bin/env sh

set -eu


echo "building sign-package"

SRC_DIR=$(pwd)
DEST_DIR=$1

echo "1"

echo "$SRC_DIR"
echo "$DEST_DIR"
which cat 

cat $SRC_DIR/dyd/assets/main > $DEST_DIR/dyd/main

echo "2"

echo "sign-package" > $DEST_DIR/dyd/traits/name
echo "socks" > $DEST_DIR/dyd/traits/author

echo "done"