#!/usr/bin/env sh

set -eu
# set -x

SRC_DIR="$DYD_STEM"
DEST_DIR="$DYD_BUILD"

TEMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TEMP_DIR"' EXIT

found_build_variant=0
for build_dep in "$SRC_DIR"/dyd/dependencies/build~*; do
	[ -e "$build_dep" ] || continue
	found_build_variant=1

	VERSION="$(cat "$build_dep"/dyd/traits/version)"
	OS="$(cat "$build_dep"/dyd/traits/os)"
	ARCH="$(cat "$build_dep"/dyd/traits/arch)"

	DEST_BIN="$DEST_DIR/dyd/assets/dryad-$VERSION-$OS-$ARCH"
	cp -L "$build_dep"/dyd/commands/dyd-stem-run "$DEST_BIN"
	chmod 0755 "$DEST_BIN"
done

if [ "$found_build_variant" -eq 0 ]; then
	echo "no dryad build variants were provided to release root" >&2
	exit 1
fi

VERSION="$(cat "$SRC_DIR"/dyd/dependencies/src/dyd/traits/version)"
cp -LR "$SRC_DIR"/dyd/dependencies/src/dyd/assets "$TEMP_DIR"/dryad
chmod -R 0755 "$TEMP_DIR"/dryad
tar -chzvf "$DEST_DIR"/dyd/assets/dryad-"$VERSION"-src.tar.gz -C "$TEMP_DIR" ./dryad

cp -LR "$SRC_DIR"/dyd/dependencies/bash_autocomplete/dyd/assets/dryad "$DEST_DIR"/dyd/assets/dryad-"$VERSION"-bash-autocomplete
cp -LR "$SRC_DIR"/dyd/dependencies/install-script/dyd/assets/install.sh "$DEST_DIR"/dyd/assets/dryad-"$VERSION"-install.sh
