#!/usr/bin/env bash
set -euf -o pipefail
SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD
cp -R $SRC_DIR/dyd/assets/commands/. $DEST_DIR/dyd/commands/
cp -R $SRC_DIR/dyd/assets/assets/. $DEST_DIR/dyd/assets/
cp $SRC_DIR/dyd/docs/about.md $DEST_DIR/dyd/docs/
ln -s $SRC_DIR/dyd/dependencies/dryad $DEST_DIR/dyd/dependencies/dryad
