#!/usr/bin/env sh

set -eu


echo "building gpg-package-verify"

SRC_DIR=$DYD_STEM
DEST_DIR=$1

cat $SRC_DIR/dyd/assets/main > $DEST_DIR/dyd/main

echo "gpg-package-verify" > $DEST_DIR/dyd/traits/name
echo "socks" > $DEST_DIR/dyd/traits/author

echo "done"

