#!/usr/bin/env bash
set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''

. $SRC_DIR/dyd/assets/assertions.sh

assert_symlink_target() {
    link_path="$1"
    expected_target="$2"

    if [ ! -L "$link_path" ]; then
        echo "[ERROR] Fail: '$link_path' is not a symlink" 1>&2
        return 1
    fi

    actual_target=$(readlink "$link_path")
    if [ "$actual_target" != "$expected_target" ]; then
        echo "[ERROR] Fail: symlink '$link_path' target expected ($expected_target), got ($actual_target)" 1>&2
        return 1
    fi
}

_setup() {
	TEMP_DIR=''
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {
	cp -R "$SRC_DIR/dyd/assets/sample-garden/." "$TEMP_DIR"
	chmod -R 755 "$TEMP_DIR"
}

_test() {
	EDITOR_PATH="$TEMP_DIR/dyd/roots/root-01/dyd/commands/dev-editor"
	(cd "$TEMP_DIR" && dryad root develop start dyd/roots/root-01 --editor="$EDITOR_PATH" --log-level="$DYD_LOG_LEVEL" < /dev/null) 1>&2
}

_verify() {
	assert_symlink_target "$TEMP_DIR/dyd/roots/root-01/dyd/assets/link.txt" "keep.txt"
	assert_file_content_equals "$TEMP_DIR/dyd/roots/root-01/dyd/assets/keep.txt" "keep"
}

_teardown() {
	if [ -d "$TEMP_DIR" ]; then
		chmod -R 755 "$TEMP_DIR"
		rm -rf "$TEMP_DIR"
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
