#!/usr/bin/env sh

set -e

echo "verifying test package"

SRC_DIR=$(pwd)
DIST_DIR=$1

# ls -al $SRC_DIR/dyd/stems

# which ls
# which cat
# which cp
# which dryad

cat $SRC_DIR/dyd/fingerprint
echo ""

PACKAGE_DIR="$SRC_DIR/dyd/stems/signed" \
GPG_KEY_ID="$TEST_KEY_ID" \
GPG_KEY_PUB="$TEST_KEY_PUB" \
GPG_KEY_PRIV="$TEST_KEY_PRIV" \
GPG_KEY_PASS="$TEST_KEY_PASS" \
	gpg-package-verify

echo -n "success" > $DIST_DIR/dyd/traits/log

# echo "$TEST_KEY_PUB" | gpg --import
# echo "$TEST_KEY_PRIV" | gpg --import --allow-secret-key-import
# echo "$TEST_KEY_PASS" | gpg --sign \
# 	--batch \
# 	--yes \
# 	--passphrase-fd 0 \
# 	-u $TEST_KEY_ID \
# 	--armor \
# 	--output $DEST_DIR/dyd/traits/signature \
# 	$DEST_DIR/dyd/fingerprint

# DEST_DIR="$DEST_DIR" sh -i


