#!/usr/bin/env bash
set -euf -o pipefail

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD

if [ -d "$SRC_DIR/dyd/assets" ]; then
	mkdir -p "$DEST_DIR/dyd/assets"
	cp -R "$SRC_DIR/dyd/assets/." "$DEST_DIR/dyd/assets/"
else
	mkdir -p "$DEST_DIR/dyd/assets"
fi

if [ -d "$SRC_DIR/dyd/traits" ]; then
	mkdir -p "$DEST_DIR/dyd/traits"
	cp -R "$SRC_DIR/dyd/traits/." "$DEST_DIR/dyd/traits/"
else
	mkdir -p "$DEST_DIR/dyd/traits"
fi

if [ -d "$SRC_DIR/dyd/requirements" ]; then
	mkdir -p "$DEST_DIR/dyd/requirements"
	cp -R "$SRC_DIR/dyd/requirements/." "$DEST_DIR/dyd/requirements/"
else
	mkdir -p "$DEST_DIR/dyd/requirements"
fi

mkdir -p "$DEST_DIR/dyd/dependencies"
dep_path="$SRC_DIR/dyd/dependencies/root-variant"
if [ -L "$dep_path" ] || [ -e "$dep_path" ]; then
	ln -s "$dep_path" "$DEST_DIR/dyd/dependencies/root-variant"
fi
