#!/usr/bin/env bash

#
# turn this on to debug script
# set -x

#
# abort on error
# https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

SRC_DIR=$DYD_STEM
TEMP_DIR=''

# import assertion functions
. $SRC_DIR/dyd/assets/assertions.sh

_setup() {
	#
	# make a temporary working directory
	# this command is linux / osx agnostic
	# https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
	# echo "\[INFO\] creating temporary working directory" 1>&2;
	TEMP_DIR=''
	TEMP_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'build-dir'`
}

_prepare() {
	# copy the sample garden to the working directory
	cp -R "$SRC_DIR/dyd/assets/sample-garden/." "$TEMP_DIR"
	chmod -R 755 "$TEMP_DIR"
	cd "$TEMP_DIR"

	:;
}

_test() {
	dryad root build dyd/roots/root-01 --log-level="$DYD_LOG_LEVEL" 1>&2;
	dryad sprout run "dyd/sprouts/root-01" --context=testctx --log-level="$DYD_LOG_LEVEL" -- argX argY 1>&2;
}

_verify() {
	assert_directory_exists "$TEMP_DIR/dyd"
	assert_file_content_equals "$TEMP_DIR/dyd/type" "garden"

	assert_directory_exists "$TEMP_DIR/dyd/heap/contexts/testctx"
	EXPECTED_CONTEXT=$(cd "$TEMP_DIR/dyd/heap/contexts/testctx" && pwd -P)
	EXPECTED_STEM=$(readlink -f "$TEMP_DIR/dyd/sprouts/root-01/dyd/dependencies/stem")
	assert_file_content_equals "$TEMP_DIR/dyd/heap/contexts/testctx/home" "$EXPECTED_CONTEXT"
	assert_file_content_equals "$TEMP_DIR/dyd/heap/contexts/testctx/context" "$EXPECTED_CONTEXT"
	assert_file_content_equals "$TEMP_DIR/dyd/heap/contexts/testctx/args" "argX argY"
	assert_file_content_equals "$TEMP_DIR/dyd/heap/contexts/testctx/stem" "$EXPECTED_STEM"

	:;
}

_teardown() {
	# echo "\[INFO\] tearing down fixtures" 1>&2;
	if [ -d "$TEMP_DIR" ]; then
		chmod -R 755 "$TEMP_DIR"
		rm -rf "$TEMP_DIR"
	fi
}

trap _teardown ERR EXIT
_setup
_prepare
_test
_verify
