#!/usr/bin/env sh

set -eu
# set -x

PATH=$DYD_STEM/dyd/assets/go/bin:$PATH

_prepare () {
	echo -n ""
}

_run () {
	GOROOT=$DYD_STEM/dyd/assets/go \
	go "$@"
}

_exit () {
	# rm -rf $CACHE_DIR || true
	echo -n ""
}

trap _exit INT HUP TERM
_prepare
_run "$@"
_exit
