# Generated by dyd/assets/tools/generate-hash-shell.sh. Do not edit by hand.

dryad_b2_load_block_shell () {
    dryad_b2_block_len=$#
    dryad_b2_m0_0=$((${1:-0} | (${2:-0} << 8)))
    dryad_b2_m0_1=$((${3:-0} | (${4:-0} << 8)))
    dryad_b2_m0_2=$((${5:-0} | (${6:-0} << 8)))
    dryad_b2_m0_3=$((${7:-0} | (${8:-0} << 8)))
    dryad_b2_m1_0=$((${9:-0} | (${10:-0} << 8)))
    dryad_b2_m1_1=$((${11:-0} | (${12:-0} << 8)))
    dryad_b2_m1_2=$((${13:-0} | (${14:-0} << 8)))
    dryad_b2_m1_3=$((${15:-0} | (${16:-0} << 8)))
    dryad_b2_m2_0=$((${17:-0} | (${18:-0} << 8)))
    dryad_b2_m2_1=$((${19:-0} | (${20:-0} << 8)))
    dryad_b2_m2_2=$((${21:-0} | (${22:-0} << 8)))
    dryad_b2_m2_3=$((${23:-0} | (${24:-0} << 8)))
    dryad_b2_m3_0=$((${25:-0} | (${26:-0} << 8)))
    dryad_b2_m3_1=$((${27:-0} | (${28:-0} << 8)))
    dryad_b2_m3_2=$((${29:-0} | (${30:-0} << 8)))
    dryad_b2_m3_3=$((${31:-0} | (${32:-0} << 8)))
    dryad_b2_m4_0=$((${33:-0} | (${34:-0} << 8)))
    dryad_b2_m4_1=$((${35:-0} | (${36:-0} << 8)))
    dryad_b2_m4_2=$((${37:-0} | (${38:-0} << 8)))
    dryad_b2_m4_3=$((${39:-0} | (${40:-0} << 8)))
    dryad_b2_m5_0=$((${41:-0} | (${42:-0} << 8)))
    dryad_b2_m5_1=$((${43:-0} | (${44:-0} << 8)))
    dryad_b2_m5_2=$((${45:-0} | (${46:-0} << 8)))
    dryad_b2_m5_3=$((${47:-0} | (${48:-0} << 8)))
    dryad_b2_m6_0=$((${49:-0} | (${50:-0} << 8)))
    dryad_b2_m6_1=$((${51:-0} | (${52:-0} << 8)))
    dryad_b2_m6_2=$((${53:-0} | (${54:-0} << 8)))
    dryad_b2_m6_3=$((${55:-0} | (${56:-0} << 8)))
    dryad_b2_m7_0=$((${57:-0} | (${58:-0} << 8)))
    dryad_b2_m7_1=$((${59:-0} | (${60:-0} << 8)))
    dryad_b2_m7_2=$((${61:-0} | (${62:-0} << 8)))
    dryad_b2_m7_3=$((${63:-0} | (${64:-0} << 8)))
    dryad_b2_m8_0=$((${65:-0} | (${66:-0} << 8)))
    dryad_b2_m8_1=$((${67:-0} | (${68:-0} << 8)))
    dryad_b2_m8_2=$((${69:-0} | (${70:-0} << 8)))
    dryad_b2_m8_3=$((${71:-0} | (${72:-0} << 8)))
    dryad_b2_m9_0=$((${73:-0} | (${74:-0} << 8)))
    dryad_b2_m9_1=$((${75:-0} | (${76:-0} << 8)))
    dryad_b2_m9_2=$((${77:-0} | (${78:-0} << 8)))
    dryad_b2_m9_3=$((${79:-0} | (${80:-0} << 8)))
    dryad_b2_m10_0=$((${81:-0} | (${82:-0} << 8)))
    dryad_b2_m10_1=$((${83:-0} | (${84:-0} << 8)))
    dryad_b2_m10_2=$((${85:-0} | (${86:-0} << 8)))
    dryad_b2_m10_3=$((${87:-0} | (${88:-0} << 8)))
    dryad_b2_m11_0=$((${89:-0} | (${90:-0} << 8)))
    dryad_b2_m11_1=$((${91:-0} | (${92:-0} << 8)))
    dryad_b2_m11_2=$((${93:-0} | (${94:-0} << 8)))
    dryad_b2_m11_3=$((${95:-0} | (${96:-0} << 8)))
    dryad_b2_m12_0=$((${97:-0} | (${98:-0} << 8)))
    dryad_b2_m12_1=$((${99:-0} | (${100:-0} << 8)))
    dryad_b2_m12_2=$((${101:-0} | (${102:-0} << 8)))
    dryad_b2_m12_3=$((${103:-0} | (${104:-0} << 8)))
    dryad_b2_m13_0=$((${105:-0} | (${106:-0} << 8)))
    dryad_b2_m13_1=$((${107:-0} | (${108:-0} << 8)))
    dryad_b2_m13_2=$((${109:-0} | (${110:-0} << 8)))
    dryad_b2_m13_3=$((${111:-0} | (${112:-0} << 8)))
    dryad_b2_m14_0=$((${113:-0} | (${114:-0} << 8)))
    dryad_b2_m14_1=$((${115:-0} | (${116:-0} << 8)))
    dryad_b2_m14_2=$((${117:-0} | (${118:-0} << 8)))
    dryad_b2_m14_3=$((${119:-0} | (${120:-0} << 8)))
    dryad_b2_m15_0=$((${121:-0} | (${122:-0} << 8)))
    dryad_b2_m15_1=$((${123:-0} | (${124:-0} << 8)))
    dryad_b2_m15_2=$((${125:-0} | (${126:-0} << 8)))
    dryad_b2_m15_3=$((${127:-0} | (${128:-0} << 8)))
}

dryad_b2_load_initial_prefixed_block_shell () {
    if [ "$#" -gt 122 ]; then
        dryad_b2_block_len=128
    else
        dryad_b2_block_len=$((5 + $#))
    fi
    if [ "$#" -gt 123 ]; then
        dryad_b2_carry_len=$(($# - 123))
    else
        dryad_b2_carry_len=0
    fi
    dryad_b2_m0_0=$((102 | (105 << 8)))
    dryad_b2_m0_1=$((108 | (101 << 8)))
    dryad_b2_m0_2=$((0 | (${1:-0} << 8)))
    dryad_b2_m0_3=$((${2:-0} | (${3:-0} << 8)))
    dryad_b2_m1_0=$((${4:-0} | (${5:-0} << 8)))
    dryad_b2_m1_1=$((${6:-0} | (${7:-0} << 8)))
    dryad_b2_m1_2=$((${8:-0} | (${9:-0} << 8)))
    dryad_b2_m1_3=$((${10:-0} | (${11:-0} << 8)))
    dryad_b2_m2_0=$((${12:-0} | (${13:-0} << 8)))
    dryad_b2_m2_1=$((${14:-0} | (${15:-0} << 8)))
    dryad_b2_m2_2=$((${16:-0} | (${17:-0} << 8)))
    dryad_b2_m2_3=$((${18:-0} | (${19:-0} << 8)))
    dryad_b2_m3_0=$((${20:-0} | (${21:-0} << 8)))
    dryad_b2_m3_1=$((${22:-0} | (${23:-0} << 8)))
    dryad_b2_m3_2=$((${24:-0} | (${25:-0} << 8)))
    dryad_b2_m3_3=$((${26:-0} | (${27:-0} << 8)))
    dryad_b2_m4_0=$((${28:-0} | (${29:-0} << 8)))
    dryad_b2_m4_1=$((${30:-0} | (${31:-0} << 8)))
    dryad_b2_m4_2=$((${32:-0} | (${33:-0} << 8)))
    dryad_b2_m4_3=$((${34:-0} | (${35:-0} << 8)))
    dryad_b2_m5_0=$((${36:-0} | (${37:-0} << 8)))
    dryad_b2_m5_1=$((${38:-0} | (${39:-0} << 8)))
    dryad_b2_m5_2=$((${40:-0} | (${41:-0} << 8)))
    dryad_b2_m5_3=$((${42:-0} | (${43:-0} << 8)))
    dryad_b2_m6_0=$((${44:-0} | (${45:-0} << 8)))
    dryad_b2_m6_1=$((${46:-0} | (${47:-0} << 8)))
    dryad_b2_m6_2=$((${48:-0} | (${49:-0} << 8)))
    dryad_b2_m6_3=$((${50:-0} | (${51:-0} << 8)))
    dryad_b2_m7_0=$((${52:-0} | (${53:-0} << 8)))
    dryad_b2_m7_1=$((${54:-0} | (${55:-0} << 8)))
    dryad_b2_m7_2=$((${56:-0} | (${57:-0} << 8)))
    dryad_b2_m7_3=$((${58:-0} | (${59:-0} << 8)))
    dryad_b2_m8_0=$((${60:-0} | (${61:-0} << 8)))
    dryad_b2_m8_1=$((${62:-0} | (${63:-0} << 8)))
    dryad_b2_m8_2=$((${64:-0} | (${65:-0} << 8)))
    dryad_b2_m8_3=$((${66:-0} | (${67:-0} << 8)))
    dryad_b2_m9_0=$((${68:-0} | (${69:-0} << 8)))
    dryad_b2_m9_1=$((${70:-0} | (${71:-0} << 8)))
    dryad_b2_m9_2=$((${72:-0} | (${73:-0} << 8)))
    dryad_b2_m9_3=$((${74:-0} | (${75:-0} << 8)))
    dryad_b2_m10_0=$((${76:-0} | (${77:-0} << 8)))
    dryad_b2_m10_1=$((${78:-0} | (${79:-0} << 8)))
    dryad_b2_m10_2=$((${80:-0} | (${81:-0} << 8)))
    dryad_b2_m10_3=$((${82:-0} | (${83:-0} << 8)))
    dryad_b2_m11_0=$((${84:-0} | (${85:-0} << 8)))
    dryad_b2_m11_1=$((${86:-0} | (${87:-0} << 8)))
    dryad_b2_m11_2=$((${88:-0} | (${89:-0} << 8)))
    dryad_b2_m11_3=$((${90:-0} | (${91:-0} << 8)))
    dryad_b2_m12_0=$((${92:-0} | (${93:-0} << 8)))
    dryad_b2_m12_1=$((${94:-0} | (${95:-0} << 8)))
    dryad_b2_m12_2=$((${96:-0} | (${97:-0} << 8)))
    dryad_b2_m12_3=$((${98:-0} | (${99:-0} << 8)))
    dryad_b2_m13_0=$((${100:-0} | (${101:-0} << 8)))
    dryad_b2_m13_1=$((${102:-0} | (${103:-0} << 8)))
    dryad_b2_m13_2=$((${104:-0} | (${105:-0} << 8)))
    dryad_b2_m13_3=$((${106:-0} | (${107:-0} << 8)))
    dryad_b2_m14_0=$((${108:-0} | (${109:-0} << 8)))
    dryad_b2_m14_1=$((${110:-0} | (${111:-0} << 8)))
    dryad_b2_m14_2=$((${112:-0} | (${113:-0} << 8)))
    dryad_b2_m14_3=$((${114:-0} | (${115:-0} << 8)))
    dryad_b2_m15_0=$((${116:-0} | (${117:-0} << 8)))
    dryad_b2_m15_1=$((${118:-0} | (${119:-0} << 8)))
    dryad_b2_m15_2=$((${120:-0} | (${121:-0} << 8)))
    dryad_b2_m15_3=$((${122:-0} | (${123:-0} << 8)))
    dryad_b2_c0=${124:-0}
    dryad_b2_c1=${125:-0}
    dryad_b2_c2=${126:-0}
    dryad_b2_c3=${127:-0}
    dryad_b2_c4=${128:-0}
}

dryad_b2_load_carried_prefixed_block_shell () {
    if [ "$#" -gt 122 ]; then
        dryad_b2_block_len=128
    else
        dryad_b2_block_len=$((5 + $#))
    fi
    if [ "$#" -gt 123 ]; then
        dryad_b2_carry_len=$(($# - 123))
    else
        dryad_b2_carry_len=0
    fi
    dryad_b2_m0_0=$(($dryad_b2_c0 | ($dryad_b2_c1 << 8)))
    dryad_b2_m0_1=$(($dryad_b2_c2 | ($dryad_b2_c3 << 8)))
    dryad_b2_m0_2=$(($dryad_b2_c4 | (${1:-0} << 8)))
    dryad_b2_m0_3=$((${2:-0} | (${3:-0} << 8)))
    dryad_b2_m1_0=$((${4:-0} | (${5:-0} << 8)))
    dryad_b2_m1_1=$((${6:-0} | (${7:-0} << 8)))
    dryad_b2_m1_2=$((${8:-0} | (${9:-0} << 8)))
    dryad_b2_m1_3=$((${10:-0} | (${11:-0} << 8)))
    dryad_b2_m2_0=$((${12:-0} | (${13:-0} << 8)))
    dryad_b2_m2_1=$((${14:-0} | (${15:-0} << 8)))
    dryad_b2_m2_2=$((${16:-0} | (${17:-0} << 8)))
    dryad_b2_m2_3=$((${18:-0} | (${19:-0} << 8)))
    dryad_b2_m3_0=$((${20:-0} | (${21:-0} << 8)))
    dryad_b2_m3_1=$((${22:-0} | (${23:-0} << 8)))
    dryad_b2_m3_2=$((${24:-0} | (${25:-0} << 8)))
    dryad_b2_m3_3=$((${26:-0} | (${27:-0} << 8)))
    dryad_b2_m4_0=$((${28:-0} | (${29:-0} << 8)))
    dryad_b2_m4_1=$((${30:-0} | (${31:-0} << 8)))
    dryad_b2_m4_2=$((${32:-0} | (${33:-0} << 8)))
    dryad_b2_m4_3=$((${34:-0} | (${35:-0} << 8)))
    dryad_b2_m5_0=$((${36:-0} | (${37:-0} << 8)))
    dryad_b2_m5_1=$((${38:-0} | (${39:-0} << 8)))
    dryad_b2_m5_2=$((${40:-0} | (${41:-0} << 8)))
    dryad_b2_m5_3=$((${42:-0} | (${43:-0} << 8)))
    dryad_b2_m6_0=$((${44:-0} | (${45:-0} << 8)))
    dryad_b2_m6_1=$((${46:-0} | (${47:-0} << 8)))
    dryad_b2_m6_2=$((${48:-0} | (${49:-0} << 8)))
    dryad_b2_m6_3=$((${50:-0} | (${51:-0} << 8)))
    dryad_b2_m7_0=$((${52:-0} | (${53:-0} << 8)))
    dryad_b2_m7_1=$((${54:-0} | (${55:-0} << 8)))
    dryad_b2_m7_2=$((${56:-0} | (${57:-0} << 8)))
    dryad_b2_m7_3=$((${58:-0} | (${59:-0} << 8)))
    dryad_b2_m8_0=$((${60:-0} | (${61:-0} << 8)))
    dryad_b2_m8_1=$((${62:-0} | (${63:-0} << 8)))
    dryad_b2_m8_2=$((${64:-0} | (${65:-0} << 8)))
    dryad_b2_m8_3=$((${66:-0} | (${67:-0} << 8)))
    dryad_b2_m9_0=$((${68:-0} | (${69:-0} << 8)))
    dryad_b2_m9_1=$((${70:-0} | (${71:-0} << 8)))
    dryad_b2_m9_2=$((${72:-0} | (${73:-0} << 8)))
    dryad_b2_m9_3=$((${74:-0} | (${75:-0} << 8)))
    dryad_b2_m10_0=$((${76:-0} | (${77:-0} << 8)))
    dryad_b2_m10_1=$((${78:-0} | (${79:-0} << 8)))
    dryad_b2_m10_2=$((${80:-0} | (${81:-0} << 8)))
    dryad_b2_m10_3=$((${82:-0} | (${83:-0} << 8)))
    dryad_b2_m11_0=$((${84:-0} | (${85:-0} << 8)))
    dryad_b2_m11_1=$((${86:-0} | (${87:-0} << 8)))
    dryad_b2_m11_2=$((${88:-0} | (${89:-0} << 8)))
    dryad_b2_m11_3=$((${90:-0} | (${91:-0} << 8)))
    dryad_b2_m12_0=$((${92:-0} | (${93:-0} << 8)))
    dryad_b2_m12_1=$((${94:-0} | (${95:-0} << 8)))
    dryad_b2_m12_2=$((${96:-0} | (${97:-0} << 8)))
    dryad_b2_m12_3=$((${98:-0} | (${99:-0} << 8)))
    dryad_b2_m13_0=$((${100:-0} | (${101:-0} << 8)))
    dryad_b2_m13_1=$((${102:-0} | (${103:-0} << 8)))
    dryad_b2_m13_2=$((${104:-0} | (${105:-0} << 8)))
    dryad_b2_m13_3=$((${106:-0} | (${107:-0} << 8)))
    dryad_b2_m14_0=$((${108:-0} | (${109:-0} << 8)))
    dryad_b2_m14_1=$((${110:-0} | (${111:-0} << 8)))
    dryad_b2_m14_2=$((${112:-0} | (${113:-0} << 8)))
    dryad_b2_m14_3=$((${114:-0} | (${115:-0} << 8)))
    dryad_b2_m15_0=$((${116:-0} | (${117:-0} << 8)))
    dryad_b2_m15_1=$((${118:-0} | (${119:-0} << 8)))
    dryad_b2_m15_2=$((${120:-0} | (${121:-0} << 8)))
    dryad_b2_m15_3=$((${122:-0} | (${123:-0} << 8)))
    dryad_b2_c0=${124:-0}
    dryad_b2_c1=${125:-0}
    dryad_b2_c2=${126:-0}
    dryad_b2_c3=${127:-0}
    dryad_b2_c4=${128:-0}
}

dryad_b2_load_final_carry_block_shell () {
    dryad_b2_block_len=$dryad_b2_carry_len
    dryad_b2_m0_0=$((dryad_b2_c0 | (dryad_b2_c1 << 8)))
    dryad_b2_m0_1=$((dryad_b2_c2 | (dryad_b2_c3 << 8)))
    dryad_b2_m0_2=$dryad_b2_c4
    dryad_b2_m0_3=0
    dryad_b2_m1_0=0
    dryad_b2_m1_1=0
    dryad_b2_m1_2=0
    dryad_b2_m1_3=0
    dryad_b2_m2_0=0
    dryad_b2_m2_1=0
    dryad_b2_m2_2=0
    dryad_b2_m2_3=0
    dryad_b2_m3_0=0
    dryad_b2_m3_1=0
    dryad_b2_m3_2=0
    dryad_b2_m3_3=0
    dryad_b2_m4_0=0
    dryad_b2_m4_1=0
    dryad_b2_m4_2=0
    dryad_b2_m4_3=0
    dryad_b2_m5_0=0
    dryad_b2_m5_1=0
    dryad_b2_m5_2=0
    dryad_b2_m5_3=0
    dryad_b2_m6_0=0
    dryad_b2_m6_1=0
    dryad_b2_m6_2=0
    dryad_b2_m6_3=0
    dryad_b2_m7_0=0
    dryad_b2_m7_1=0
    dryad_b2_m7_2=0
    dryad_b2_m7_3=0
    dryad_b2_m8_0=0
    dryad_b2_m8_1=0
    dryad_b2_m8_2=0
    dryad_b2_m8_3=0
    dryad_b2_m9_0=0
    dryad_b2_m9_1=0
    dryad_b2_m9_2=0
    dryad_b2_m9_3=0
    dryad_b2_m10_0=0
    dryad_b2_m10_1=0
    dryad_b2_m10_2=0
    dryad_b2_m10_3=0
    dryad_b2_m11_0=0
    dryad_b2_m11_1=0
    dryad_b2_m11_2=0
    dryad_b2_m11_3=0
    dryad_b2_m12_0=0
    dryad_b2_m12_1=0
    dryad_b2_m12_2=0
    dryad_b2_m12_3=0
    dryad_b2_m13_0=0
    dryad_b2_m13_1=0
    dryad_b2_m13_2=0
    dryad_b2_m13_3=0
    dryad_b2_m14_0=0
    dryad_b2_m14_1=0
    dryad_b2_m14_2=0
    dryad_b2_m14_3=0
    dryad_b2_m15_0=0
    dryad_b2_m15_1=0
    dryad_b2_m15_2=0
    dryad_b2_m15_3=0
}

dryad_b2_reset_shell () {
    dryad_b2_iv0_0=51464
    dryad_b2_iv0_1=62396
    dryad_b2_iv0_2=58983
    dryad_b2_iv0_3=27145
    dryad_b2_iv1_0=42811
    dryad_b2_iv1_1=33994
    dryad_b2_iv1_2=44677
    dryad_b2_iv1_3=47975
    dryad_b2_iv2_0=63531
    dryad_b2_iv2_1=65172
    dryad_b2_iv2_2=62322
    dryad_b2_iv2_3=15470
    dryad_b2_iv3_0=14065
    dryad_b2_iv3_1=24349
    dryad_b2_iv3_2=62778
    dryad_b2_iv3_3=42319
    dryad_b2_iv4_0=33489
    dryad_b2_iv4_1=44518
    dryad_b2_iv4_2=21119
    dryad_b2_iv4_3=20750
    dryad_b2_iv5_0=27679
    dryad_b2_iv5_1=11070
    dryad_b2_iv5_2=26764
    dryad_b2_iv5_3=39685
    dryad_b2_iv6_0=48491
    dryad_b2_iv6_1=64321
    dryad_b2_iv6_2=55723
    dryad_b2_iv6_3=8067
    dryad_b2_iv7_0=8569
    dryad_b2_iv7_1=4990
    dryad_b2_iv7_2=52505
    dryad_b2_iv7_3=23520
    dryad_b2_h0_0=$dryad_b2_iv0_0
    dryad_b2_h0_1=$dryad_b2_iv0_1
    dryad_b2_h0_2=$dryad_b2_iv0_2
    dryad_b2_h0_3=$dryad_b2_iv0_3
    dryad_b2_h1_0=$dryad_b2_iv1_0
    dryad_b2_h1_1=$dryad_b2_iv1_1
    dryad_b2_h1_2=$dryad_b2_iv1_2
    dryad_b2_h1_3=$dryad_b2_iv1_3
    dryad_b2_h2_0=$dryad_b2_iv2_0
    dryad_b2_h2_1=$dryad_b2_iv2_1
    dryad_b2_h2_2=$dryad_b2_iv2_2
    dryad_b2_h2_3=$dryad_b2_iv2_3
    dryad_b2_h3_0=$dryad_b2_iv3_0
    dryad_b2_h3_1=$dryad_b2_iv3_1
    dryad_b2_h3_2=$dryad_b2_iv3_2
    dryad_b2_h3_3=$dryad_b2_iv3_3
    dryad_b2_h4_0=$dryad_b2_iv4_0
    dryad_b2_h4_1=$dryad_b2_iv4_1
    dryad_b2_h4_2=$dryad_b2_iv4_2
    dryad_b2_h4_3=$dryad_b2_iv4_3
    dryad_b2_h5_0=$dryad_b2_iv5_0
    dryad_b2_h5_1=$dryad_b2_iv5_1
    dryad_b2_h5_2=$dryad_b2_iv5_2
    dryad_b2_h5_3=$dryad_b2_iv5_3
    dryad_b2_h6_0=$dryad_b2_iv6_0
    dryad_b2_h6_1=$dryad_b2_iv6_1
    dryad_b2_h6_2=$dryad_b2_iv6_2
    dryad_b2_h6_3=$dryad_b2_iv6_3
    dryad_b2_h7_0=$dryad_b2_iv7_0
    dryad_b2_h7_1=$dryad_b2_iv7_1
    dryad_b2_h7_2=$dryad_b2_iv7_2
    dryad_b2_h7_3=$dryad_b2_iv7_3
    dryad_b2_h0_0=$((dryad_b2_h0_0 ^ 16))
    dryad_b2_h0_1=$((dryad_b2_h0_1 ^ 257))
    dryad_b2_t0=0
    dryad_b2_t1=0
    dryad_b2_t2=0
    dryad_b2_t3=0
}

dryad_b2_add_counter_shell () {
    dryad_b2_counter_add=$1
    dryad_b2_sum=$((dryad_b2_t0 + dryad_b2_counter_add))
    dryad_b2_t0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_t1 + dryad_b2_carry))
    dryad_b2_t1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_t2 + dryad_b2_carry))
    dryad_b2_t2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_t3=$(((dryad_b2_t3 + dryad_b2_carry) & 65535))
}

dryad_b2_G_0_4_8_12 () {
    dryad_b2_sum=$((dryad_b2_v0_0 + dryad_b2_v4_0 + ${1}))
    dryad_b2_v0_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_1 + dryad_b2_v4_1 + ${2} + dryad_b2_carry))
    dryad_b2_v0_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_2 + dryad_b2_v4_2 + ${3} + dryad_b2_carry))
    dryad_b2_v0_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_3 + dryad_b2_v4_3 + ${4} + dryad_b2_carry))
    dryad_b2_v0_3=$((dryad_b2_sum & 65535))
    dryad_b2_v12_0=$((dryad_b2_v12_0 ^ dryad_b2_v0_0))
    dryad_b2_v12_1=$((dryad_b2_v12_1 ^ dryad_b2_v0_1))
    dryad_b2_v12_2=$((dryad_b2_v12_2 ^ dryad_b2_v0_2))
    dryad_b2_v12_3=$((dryad_b2_v12_3 ^ dryad_b2_v0_3))
    dryad_b2_r0=$dryad_b2_v12_0
    dryad_b2_r1=$dryad_b2_v12_1
    dryad_b2_r2=$dryad_b2_v12_2
    dryad_b2_r3=$dryad_b2_v12_3
    dryad_b2_v12_0=$dryad_b2_r2
    dryad_b2_v12_1=$dryad_b2_r3
    dryad_b2_v12_2=$dryad_b2_r0
    dryad_b2_v12_3=$dryad_b2_r1
    dryad_b2_sum=$((dryad_b2_v8_0 + dryad_b2_v12_0))
    dryad_b2_v8_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_1 + dryad_b2_v12_1 + dryad_b2_carry))
    dryad_b2_v8_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_2 + dryad_b2_v12_2 + dryad_b2_carry))
    dryad_b2_v8_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_3 + dryad_b2_v12_3 + dryad_b2_carry))
    dryad_b2_v8_3=$((dryad_b2_sum & 65535))
    dryad_b2_v4_0=$((dryad_b2_v4_0 ^ dryad_b2_v8_0))
    dryad_b2_v4_1=$((dryad_b2_v4_1 ^ dryad_b2_v8_1))
    dryad_b2_v4_2=$((dryad_b2_v4_2 ^ dryad_b2_v8_2))
    dryad_b2_v4_3=$((dryad_b2_v4_3 ^ dryad_b2_v8_3))
    dryad_b2_r0=$dryad_b2_v4_0
    dryad_b2_r1=$dryad_b2_v4_1
    dryad_b2_r2=$dryad_b2_v4_2
    dryad_b2_r3=$dryad_b2_v4_3
    dryad_b2_v4_0=$(((dryad_b2_r1 >> 8) | ((dryad_b2_r2 & 255) << 8)))
    dryad_b2_v4_1=$(((dryad_b2_r2 >> 8) | ((dryad_b2_r3 & 255) << 8)))
    dryad_b2_v4_2=$(((dryad_b2_r3 >> 8) | ((dryad_b2_r0 & 255) << 8)))
    dryad_b2_v4_3=$(((dryad_b2_r0 >> 8) | ((dryad_b2_r1 & 255) << 8)))
    dryad_b2_sum=$((dryad_b2_v0_0 + dryad_b2_v4_0 + ${5}))
    dryad_b2_v0_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_1 + dryad_b2_v4_1 + ${6} + dryad_b2_carry))
    dryad_b2_v0_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_2 + dryad_b2_v4_2 + ${7} + dryad_b2_carry))
    dryad_b2_v0_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_3 + dryad_b2_v4_3 + ${8} + dryad_b2_carry))
    dryad_b2_v0_3=$((dryad_b2_sum & 65535))
    dryad_b2_v12_0=$((dryad_b2_v12_0 ^ dryad_b2_v0_0))
    dryad_b2_v12_1=$((dryad_b2_v12_1 ^ dryad_b2_v0_1))
    dryad_b2_v12_2=$((dryad_b2_v12_2 ^ dryad_b2_v0_2))
    dryad_b2_v12_3=$((dryad_b2_v12_3 ^ dryad_b2_v0_3))
    dryad_b2_r0=$dryad_b2_v12_0
    dryad_b2_r1=$dryad_b2_v12_1
    dryad_b2_r2=$dryad_b2_v12_2
    dryad_b2_r3=$dryad_b2_v12_3
    dryad_b2_v12_0=$dryad_b2_r1
    dryad_b2_v12_1=$dryad_b2_r2
    dryad_b2_v12_2=$dryad_b2_r3
    dryad_b2_v12_3=$dryad_b2_r0
    dryad_b2_sum=$((dryad_b2_v8_0 + dryad_b2_v12_0))
    dryad_b2_v8_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_1 + dryad_b2_v12_1 + dryad_b2_carry))
    dryad_b2_v8_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_2 + dryad_b2_v12_2 + dryad_b2_carry))
    dryad_b2_v8_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_3 + dryad_b2_v12_3 + dryad_b2_carry))
    dryad_b2_v8_3=$((dryad_b2_sum & 65535))
    dryad_b2_v4_0=$((dryad_b2_v4_0 ^ dryad_b2_v8_0))
    dryad_b2_v4_1=$((dryad_b2_v4_1 ^ dryad_b2_v8_1))
    dryad_b2_v4_2=$((dryad_b2_v4_2 ^ dryad_b2_v8_2))
    dryad_b2_v4_3=$((dryad_b2_v4_3 ^ dryad_b2_v8_3))
    dryad_b2_r0=$dryad_b2_v4_0
    dryad_b2_r1=$dryad_b2_v4_1
    dryad_b2_r2=$dryad_b2_v4_2
    dryad_b2_r3=$dryad_b2_v4_3
    dryad_b2_v4_0=$((((dryad_b2_r0 << 1) & 65535) | (dryad_b2_r3 >> 15)))
    dryad_b2_v4_1=$((((dryad_b2_r1 << 1) & 65535) | (dryad_b2_r0 >> 15)))
    dryad_b2_v4_2=$((((dryad_b2_r2 << 1) & 65535) | (dryad_b2_r1 >> 15)))
    dryad_b2_v4_3=$((((dryad_b2_r3 << 1) & 65535) | (dryad_b2_r2 >> 15)))
}

dryad_b2_G_1_5_9_13 () {
    dryad_b2_sum=$((dryad_b2_v1_0 + dryad_b2_v5_0 + ${1}))
    dryad_b2_v1_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_1 + dryad_b2_v5_1 + ${2} + dryad_b2_carry))
    dryad_b2_v1_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_2 + dryad_b2_v5_2 + ${3} + dryad_b2_carry))
    dryad_b2_v1_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_3 + dryad_b2_v5_3 + ${4} + dryad_b2_carry))
    dryad_b2_v1_3=$((dryad_b2_sum & 65535))
    dryad_b2_v13_0=$((dryad_b2_v13_0 ^ dryad_b2_v1_0))
    dryad_b2_v13_1=$((dryad_b2_v13_1 ^ dryad_b2_v1_1))
    dryad_b2_v13_2=$((dryad_b2_v13_2 ^ dryad_b2_v1_2))
    dryad_b2_v13_3=$((dryad_b2_v13_3 ^ dryad_b2_v1_3))
    dryad_b2_r0=$dryad_b2_v13_0
    dryad_b2_r1=$dryad_b2_v13_1
    dryad_b2_r2=$dryad_b2_v13_2
    dryad_b2_r3=$dryad_b2_v13_3
    dryad_b2_v13_0=$dryad_b2_r2
    dryad_b2_v13_1=$dryad_b2_r3
    dryad_b2_v13_2=$dryad_b2_r0
    dryad_b2_v13_3=$dryad_b2_r1
    dryad_b2_sum=$((dryad_b2_v9_0 + dryad_b2_v13_0))
    dryad_b2_v9_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_1 + dryad_b2_v13_1 + dryad_b2_carry))
    dryad_b2_v9_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_2 + dryad_b2_v13_2 + dryad_b2_carry))
    dryad_b2_v9_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_3 + dryad_b2_v13_3 + dryad_b2_carry))
    dryad_b2_v9_3=$((dryad_b2_sum & 65535))
    dryad_b2_v5_0=$((dryad_b2_v5_0 ^ dryad_b2_v9_0))
    dryad_b2_v5_1=$((dryad_b2_v5_1 ^ dryad_b2_v9_1))
    dryad_b2_v5_2=$((dryad_b2_v5_2 ^ dryad_b2_v9_2))
    dryad_b2_v5_3=$((dryad_b2_v5_3 ^ dryad_b2_v9_3))
    dryad_b2_r0=$dryad_b2_v5_0
    dryad_b2_r1=$dryad_b2_v5_1
    dryad_b2_r2=$dryad_b2_v5_2
    dryad_b2_r3=$dryad_b2_v5_3
    dryad_b2_v5_0=$(((dryad_b2_r1 >> 8) | ((dryad_b2_r2 & 255) << 8)))
    dryad_b2_v5_1=$(((dryad_b2_r2 >> 8) | ((dryad_b2_r3 & 255) << 8)))
    dryad_b2_v5_2=$(((dryad_b2_r3 >> 8) | ((dryad_b2_r0 & 255) << 8)))
    dryad_b2_v5_3=$(((dryad_b2_r0 >> 8) | ((dryad_b2_r1 & 255) << 8)))
    dryad_b2_sum=$((dryad_b2_v1_0 + dryad_b2_v5_0 + ${5}))
    dryad_b2_v1_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_1 + dryad_b2_v5_1 + ${6} + dryad_b2_carry))
    dryad_b2_v1_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_2 + dryad_b2_v5_2 + ${7} + dryad_b2_carry))
    dryad_b2_v1_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_3 + dryad_b2_v5_3 + ${8} + dryad_b2_carry))
    dryad_b2_v1_3=$((dryad_b2_sum & 65535))
    dryad_b2_v13_0=$((dryad_b2_v13_0 ^ dryad_b2_v1_0))
    dryad_b2_v13_1=$((dryad_b2_v13_1 ^ dryad_b2_v1_1))
    dryad_b2_v13_2=$((dryad_b2_v13_2 ^ dryad_b2_v1_2))
    dryad_b2_v13_3=$((dryad_b2_v13_3 ^ dryad_b2_v1_3))
    dryad_b2_r0=$dryad_b2_v13_0
    dryad_b2_r1=$dryad_b2_v13_1
    dryad_b2_r2=$dryad_b2_v13_2
    dryad_b2_r3=$dryad_b2_v13_3
    dryad_b2_v13_0=$dryad_b2_r1
    dryad_b2_v13_1=$dryad_b2_r2
    dryad_b2_v13_2=$dryad_b2_r3
    dryad_b2_v13_3=$dryad_b2_r0
    dryad_b2_sum=$((dryad_b2_v9_0 + dryad_b2_v13_0))
    dryad_b2_v9_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_1 + dryad_b2_v13_1 + dryad_b2_carry))
    dryad_b2_v9_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_2 + dryad_b2_v13_2 + dryad_b2_carry))
    dryad_b2_v9_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_3 + dryad_b2_v13_3 + dryad_b2_carry))
    dryad_b2_v9_3=$((dryad_b2_sum & 65535))
    dryad_b2_v5_0=$((dryad_b2_v5_0 ^ dryad_b2_v9_0))
    dryad_b2_v5_1=$((dryad_b2_v5_1 ^ dryad_b2_v9_1))
    dryad_b2_v5_2=$((dryad_b2_v5_2 ^ dryad_b2_v9_2))
    dryad_b2_v5_3=$((dryad_b2_v5_3 ^ dryad_b2_v9_3))
    dryad_b2_r0=$dryad_b2_v5_0
    dryad_b2_r1=$dryad_b2_v5_1
    dryad_b2_r2=$dryad_b2_v5_2
    dryad_b2_r3=$dryad_b2_v5_3
    dryad_b2_v5_0=$((((dryad_b2_r0 << 1) & 65535) | (dryad_b2_r3 >> 15)))
    dryad_b2_v5_1=$((((dryad_b2_r1 << 1) & 65535) | (dryad_b2_r0 >> 15)))
    dryad_b2_v5_2=$((((dryad_b2_r2 << 1) & 65535) | (dryad_b2_r1 >> 15)))
    dryad_b2_v5_3=$((((dryad_b2_r3 << 1) & 65535) | (dryad_b2_r2 >> 15)))
}

dryad_b2_G_2_6_10_14 () {
    dryad_b2_sum=$((dryad_b2_v2_0 + dryad_b2_v6_0 + ${1}))
    dryad_b2_v2_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_1 + dryad_b2_v6_1 + ${2} + dryad_b2_carry))
    dryad_b2_v2_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_2 + dryad_b2_v6_2 + ${3} + dryad_b2_carry))
    dryad_b2_v2_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_3 + dryad_b2_v6_3 + ${4} + dryad_b2_carry))
    dryad_b2_v2_3=$((dryad_b2_sum & 65535))
    dryad_b2_v14_0=$((dryad_b2_v14_0 ^ dryad_b2_v2_0))
    dryad_b2_v14_1=$((dryad_b2_v14_1 ^ dryad_b2_v2_1))
    dryad_b2_v14_2=$((dryad_b2_v14_2 ^ dryad_b2_v2_2))
    dryad_b2_v14_3=$((dryad_b2_v14_3 ^ dryad_b2_v2_3))
    dryad_b2_r0=$dryad_b2_v14_0
    dryad_b2_r1=$dryad_b2_v14_1
    dryad_b2_r2=$dryad_b2_v14_2
    dryad_b2_r3=$dryad_b2_v14_3
    dryad_b2_v14_0=$dryad_b2_r2
    dryad_b2_v14_1=$dryad_b2_r3
    dryad_b2_v14_2=$dryad_b2_r0
    dryad_b2_v14_3=$dryad_b2_r1
    dryad_b2_sum=$((dryad_b2_v10_0 + dryad_b2_v14_0))
    dryad_b2_v10_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_1 + dryad_b2_v14_1 + dryad_b2_carry))
    dryad_b2_v10_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_2 + dryad_b2_v14_2 + dryad_b2_carry))
    dryad_b2_v10_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_3 + dryad_b2_v14_3 + dryad_b2_carry))
    dryad_b2_v10_3=$((dryad_b2_sum & 65535))
    dryad_b2_v6_0=$((dryad_b2_v6_0 ^ dryad_b2_v10_0))
    dryad_b2_v6_1=$((dryad_b2_v6_1 ^ dryad_b2_v10_1))
    dryad_b2_v6_2=$((dryad_b2_v6_2 ^ dryad_b2_v10_2))
    dryad_b2_v6_3=$((dryad_b2_v6_3 ^ dryad_b2_v10_3))
    dryad_b2_r0=$dryad_b2_v6_0
    dryad_b2_r1=$dryad_b2_v6_1
    dryad_b2_r2=$dryad_b2_v6_2
    dryad_b2_r3=$dryad_b2_v6_3
    dryad_b2_v6_0=$(((dryad_b2_r1 >> 8) | ((dryad_b2_r2 & 255) << 8)))
    dryad_b2_v6_1=$(((dryad_b2_r2 >> 8) | ((dryad_b2_r3 & 255) << 8)))
    dryad_b2_v6_2=$(((dryad_b2_r3 >> 8) | ((dryad_b2_r0 & 255) << 8)))
    dryad_b2_v6_3=$(((dryad_b2_r0 >> 8) | ((dryad_b2_r1 & 255) << 8)))
    dryad_b2_sum=$((dryad_b2_v2_0 + dryad_b2_v6_0 + ${5}))
    dryad_b2_v2_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_1 + dryad_b2_v6_1 + ${6} + dryad_b2_carry))
    dryad_b2_v2_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_2 + dryad_b2_v6_2 + ${7} + dryad_b2_carry))
    dryad_b2_v2_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_3 + dryad_b2_v6_3 + ${8} + dryad_b2_carry))
    dryad_b2_v2_3=$((dryad_b2_sum & 65535))
    dryad_b2_v14_0=$((dryad_b2_v14_0 ^ dryad_b2_v2_0))
    dryad_b2_v14_1=$((dryad_b2_v14_1 ^ dryad_b2_v2_1))
    dryad_b2_v14_2=$((dryad_b2_v14_2 ^ dryad_b2_v2_2))
    dryad_b2_v14_3=$((dryad_b2_v14_3 ^ dryad_b2_v2_3))
    dryad_b2_r0=$dryad_b2_v14_0
    dryad_b2_r1=$dryad_b2_v14_1
    dryad_b2_r2=$dryad_b2_v14_2
    dryad_b2_r3=$dryad_b2_v14_3
    dryad_b2_v14_0=$dryad_b2_r1
    dryad_b2_v14_1=$dryad_b2_r2
    dryad_b2_v14_2=$dryad_b2_r3
    dryad_b2_v14_3=$dryad_b2_r0
    dryad_b2_sum=$((dryad_b2_v10_0 + dryad_b2_v14_0))
    dryad_b2_v10_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_1 + dryad_b2_v14_1 + dryad_b2_carry))
    dryad_b2_v10_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_2 + dryad_b2_v14_2 + dryad_b2_carry))
    dryad_b2_v10_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_3 + dryad_b2_v14_3 + dryad_b2_carry))
    dryad_b2_v10_3=$((dryad_b2_sum & 65535))
    dryad_b2_v6_0=$((dryad_b2_v6_0 ^ dryad_b2_v10_0))
    dryad_b2_v6_1=$((dryad_b2_v6_1 ^ dryad_b2_v10_1))
    dryad_b2_v6_2=$((dryad_b2_v6_2 ^ dryad_b2_v10_2))
    dryad_b2_v6_3=$((dryad_b2_v6_3 ^ dryad_b2_v10_3))
    dryad_b2_r0=$dryad_b2_v6_0
    dryad_b2_r1=$dryad_b2_v6_1
    dryad_b2_r2=$dryad_b2_v6_2
    dryad_b2_r3=$dryad_b2_v6_3
    dryad_b2_v6_0=$((((dryad_b2_r0 << 1) & 65535) | (dryad_b2_r3 >> 15)))
    dryad_b2_v6_1=$((((dryad_b2_r1 << 1) & 65535) | (dryad_b2_r0 >> 15)))
    dryad_b2_v6_2=$((((dryad_b2_r2 << 1) & 65535) | (dryad_b2_r1 >> 15)))
    dryad_b2_v6_3=$((((dryad_b2_r3 << 1) & 65535) | (dryad_b2_r2 >> 15)))
}

dryad_b2_G_3_7_11_15 () {
    dryad_b2_sum=$((dryad_b2_v3_0 + dryad_b2_v7_0 + ${1}))
    dryad_b2_v3_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_1 + dryad_b2_v7_1 + ${2} + dryad_b2_carry))
    dryad_b2_v3_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_2 + dryad_b2_v7_2 + ${3} + dryad_b2_carry))
    dryad_b2_v3_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_3 + dryad_b2_v7_3 + ${4} + dryad_b2_carry))
    dryad_b2_v3_3=$((dryad_b2_sum & 65535))
    dryad_b2_v15_0=$((dryad_b2_v15_0 ^ dryad_b2_v3_0))
    dryad_b2_v15_1=$((dryad_b2_v15_1 ^ dryad_b2_v3_1))
    dryad_b2_v15_2=$((dryad_b2_v15_2 ^ dryad_b2_v3_2))
    dryad_b2_v15_3=$((dryad_b2_v15_3 ^ dryad_b2_v3_3))
    dryad_b2_r0=$dryad_b2_v15_0
    dryad_b2_r1=$dryad_b2_v15_1
    dryad_b2_r2=$dryad_b2_v15_2
    dryad_b2_r3=$dryad_b2_v15_3
    dryad_b2_v15_0=$dryad_b2_r2
    dryad_b2_v15_1=$dryad_b2_r3
    dryad_b2_v15_2=$dryad_b2_r0
    dryad_b2_v15_3=$dryad_b2_r1
    dryad_b2_sum=$((dryad_b2_v11_0 + dryad_b2_v15_0))
    dryad_b2_v11_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_1 + dryad_b2_v15_1 + dryad_b2_carry))
    dryad_b2_v11_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_2 + dryad_b2_v15_2 + dryad_b2_carry))
    dryad_b2_v11_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_3 + dryad_b2_v15_3 + dryad_b2_carry))
    dryad_b2_v11_3=$((dryad_b2_sum & 65535))
    dryad_b2_v7_0=$((dryad_b2_v7_0 ^ dryad_b2_v11_0))
    dryad_b2_v7_1=$((dryad_b2_v7_1 ^ dryad_b2_v11_1))
    dryad_b2_v7_2=$((dryad_b2_v7_2 ^ dryad_b2_v11_2))
    dryad_b2_v7_3=$((dryad_b2_v7_3 ^ dryad_b2_v11_3))
    dryad_b2_r0=$dryad_b2_v7_0
    dryad_b2_r1=$dryad_b2_v7_1
    dryad_b2_r2=$dryad_b2_v7_2
    dryad_b2_r3=$dryad_b2_v7_3
    dryad_b2_v7_0=$(((dryad_b2_r1 >> 8) | ((dryad_b2_r2 & 255) << 8)))
    dryad_b2_v7_1=$(((dryad_b2_r2 >> 8) | ((dryad_b2_r3 & 255) << 8)))
    dryad_b2_v7_2=$(((dryad_b2_r3 >> 8) | ((dryad_b2_r0 & 255) << 8)))
    dryad_b2_v7_3=$(((dryad_b2_r0 >> 8) | ((dryad_b2_r1 & 255) << 8)))
    dryad_b2_sum=$((dryad_b2_v3_0 + dryad_b2_v7_0 + ${5}))
    dryad_b2_v3_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_1 + dryad_b2_v7_1 + ${6} + dryad_b2_carry))
    dryad_b2_v3_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_2 + dryad_b2_v7_2 + ${7} + dryad_b2_carry))
    dryad_b2_v3_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_3 + dryad_b2_v7_3 + ${8} + dryad_b2_carry))
    dryad_b2_v3_3=$((dryad_b2_sum & 65535))
    dryad_b2_v15_0=$((dryad_b2_v15_0 ^ dryad_b2_v3_0))
    dryad_b2_v15_1=$((dryad_b2_v15_1 ^ dryad_b2_v3_1))
    dryad_b2_v15_2=$((dryad_b2_v15_2 ^ dryad_b2_v3_2))
    dryad_b2_v15_3=$((dryad_b2_v15_3 ^ dryad_b2_v3_3))
    dryad_b2_r0=$dryad_b2_v15_0
    dryad_b2_r1=$dryad_b2_v15_1
    dryad_b2_r2=$dryad_b2_v15_2
    dryad_b2_r3=$dryad_b2_v15_3
    dryad_b2_v15_0=$dryad_b2_r1
    dryad_b2_v15_1=$dryad_b2_r2
    dryad_b2_v15_2=$dryad_b2_r3
    dryad_b2_v15_3=$dryad_b2_r0
    dryad_b2_sum=$((dryad_b2_v11_0 + dryad_b2_v15_0))
    dryad_b2_v11_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_1 + dryad_b2_v15_1 + dryad_b2_carry))
    dryad_b2_v11_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_2 + dryad_b2_v15_2 + dryad_b2_carry))
    dryad_b2_v11_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_3 + dryad_b2_v15_3 + dryad_b2_carry))
    dryad_b2_v11_3=$((dryad_b2_sum & 65535))
    dryad_b2_v7_0=$((dryad_b2_v7_0 ^ dryad_b2_v11_0))
    dryad_b2_v7_1=$((dryad_b2_v7_1 ^ dryad_b2_v11_1))
    dryad_b2_v7_2=$((dryad_b2_v7_2 ^ dryad_b2_v11_2))
    dryad_b2_v7_3=$((dryad_b2_v7_3 ^ dryad_b2_v11_3))
    dryad_b2_r0=$dryad_b2_v7_0
    dryad_b2_r1=$dryad_b2_v7_1
    dryad_b2_r2=$dryad_b2_v7_2
    dryad_b2_r3=$dryad_b2_v7_3
    dryad_b2_v7_0=$((((dryad_b2_r0 << 1) & 65535) | (dryad_b2_r3 >> 15)))
    dryad_b2_v7_1=$((((dryad_b2_r1 << 1) & 65535) | (dryad_b2_r0 >> 15)))
    dryad_b2_v7_2=$((((dryad_b2_r2 << 1) & 65535) | (dryad_b2_r1 >> 15)))
    dryad_b2_v7_3=$((((dryad_b2_r3 << 1) & 65535) | (dryad_b2_r2 >> 15)))
}

dryad_b2_G_0_5_10_15 () {
    dryad_b2_sum=$((dryad_b2_v0_0 + dryad_b2_v5_0 + ${1}))
    dryad_b2_v0_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_1 + dryad_b2_v5_1 + ${2} + dryad_b2_carry))
    dryad_b2_v0_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_2 + dryad_b2_v5_2 + ${3} + dryad_b2_carry))
    dryad_b2_v0_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_3 + dryad_b2_v5_3 + ${4} + dryad_b2_carry))
    dryad_b2_v0_3=$((dryad_b2_sum & 65535))
    dryad_b2_v15_0=$((dryad_b2_v15_0 ^ dryad_b2_v0_0))
    dryad_b2_v15_1=$((dryad_b2_v15_1 ^ dryad_b2_v0_1))
    dryad_b2_v15_2=$((dryad_b2_v15_2 ^ dryad_b2_v0_2))
    dryad_b2_v15_3=$((dryad_b2_v15_3 ^ dryad_b2_v0_3))
    dryad_b2_r0=$dryad_b2_v15_0
    dryad_b2_r1=$dryad_b2_v15_1
    dryad_b2_r2=$dryad_b2_v15_2
    dryad_b2_r3=$dryad_b2_v15_3
    dryad_b2_v15_0=$dryad_b2_r2
    dryad_b2_v15_1=$dryad_b2_r3
    dryad_b2_v15_2=$dryad_b2_r0
    dryad_b2_v15_3=$dryad_b2_r1
    dryad_b2_sum=$((dryad_b2_v10_0 + dryad_b2_v15_0))
    dryad_b2_v10_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_1 + dryad_b2_v15_1 + dryad_b2_carry))
    dryad_b2_v10_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_2 + dryad_b2_v15_2 + dryad_b2_carry))
    dryad_b2_v10_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_3 + dryad_b2_v15_3 + dryad_b2_carry))
    dryad_b2_v10_3=$((dryad_b2_sum & 65535))
    dryad_b2_v5_0=$((dryad_b2_v5_0 ^ dryad_b2_v10_0))
    dryad_b2_v5_1=$((dryad_b2_v5_1 ^ dryad_b2_v10_1))
    dryad_b2_v5_2=$((dryad_b2_v5_2 ^ dryad_b2_v10_2))
    dryad_b2_v5_3=$((dryad_b2_v5_3 ^ dryad_b2_v10_3))
    dryad_b2_r0=$dryad_b2_v5_0
    dryad_b2_r1=$dryad_b2_v5_1
    dryad_b2_r2=$dryad_b2_v5_2
    dryad_b2_r3=$dryad_b2_v5_3
    dryad_b2_v5_0=$(((dryad_b2_r1 >> 8) | ((dryad_b2_r2 & 255) << 8)))
    dryad_b2_v5_1=$(((dryad_b2_r2 >> 8) | ((dryad_b2_r3 & 255) << 8)))
    dryad_b2_v5_2=$(((dryad_b2_r3 >> 8) | ((dryad_b2_r0 & 255) << 8)))
    dryad_b2_v5_3=$(((dryad_b2_r0 >> 8) | ((dryad_b2_r1 & 255) << 8)))
    dryad_b2_sum=$((dryad_b2_v0_0 + dryad_b2_v5_0 + ${5}))
    dryad_b2_v0_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_1 + dryad_b2_v5_1 + ${6} + dryad_b2_carry))
    dryad_b2_v0_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_2 + dryad_b2_v5_2 + ${7} + dryad_b2_carry))
    dryad_b2_v0_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v0_3 + dryad_b2_v5_3 + ${8} + dryad_b2_carry))
    dryad_b2_v0_3=$((dryad_b2_sum & 65535))
    dryad_b2_v15_0=$((dryad_b2_v15_0 ^ dryad_b2_v0_0))
    dryad_b2_v15_1=$((dryad_b2_v15_1 ^ dryad_b2_v0_1))
    dryad_b2_v15_2=$((dryad_b2_v15_2 ^ dryad_b2_v0_2))
    dryad_b2_v15_3=$((dryad_b2_v15_3 ^ dryad_b2_v0_3))
    dryad_b2_r0=$dryad_b2_v15_0
    dryad_b2_r1=$dryad_b2_v15_1
    dryad_b2_r2=$dryad_b2_v15_2
    dryad_b2_r3=$dryad_b2_v15_3
    dryad_b2_v15_0=$dryad_b2_r1
    dryad_b2_v15_1=$dryad_b2_r2
    dryad_b2_v15_2=$dryad_b2_r3
    dryad_b2_v15_3=$dryad_b2_r0
    dryad_b2_sum=$((dryad_b2_v10_0 + dryad_b2_v15_0))
    dryad_b2_v10_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_1 + dryad_b2_v15_1 + dryad_b2_carry))
    dryad_b2_v10_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_2 + dryad_b2_v15_2 + dryad_b2_carry))
    dryad_b2_v10_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v10_3 + dryad_b2_v15_3 + dryad_b2_carry))
    dryad_b2_v10_3=$((dryad_b2_sum & 65535))
    dryad_b2_v5_0=$((dryad_b2_v5_0 ^ dryad_b2_v10_0))
    dryad_b2_v5_1=$((dryad_b2_v5_1 ^ dryad_b2_v10_1))
    dryad_b2_v5_2=$((dryad_b2_v5_2 ^ dryad_b2_v10_2))
    dryad_b2_v5_3=$((dryad_b2_v5_3 ^ dryad_b2_v10_3))
    dryad_b2_r0=$dryad_b2_v5_0
    dryad_b2_r1=$dryad_b2_v5_1
    dryad_b2_r2=$dryad_b2_v5_2
    dryad_b2_r3=$dryad_b2_v5_3
    dryad_b2_v5_0=$((((dryad_b2_r0 << 1) & 65535) | (dryad_b2_r3 >> 15)))
    dryad_b2_v5_1=$((((dryad_b2_r1 << 1) & 65535) | (dryad_b2_r0 >> 15)))
    dryad_b2_v5_2=$((((dryad_b2_r2 << 1) & 65535) | (dryad_b2_r1 >> 15)))
    dryad_b2_v5_3=$((((dryad_b2_r3 << 1) & 65535) | (dryad_b2_r2 >> 15)))
}

dryad_b2_G_1_6_11_12 () {
    dryad_b2_sum=$((dryad_b2_v1_0 + dryad_b2_v6_0 + ${1}))
    dryad_b2_v1_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_1 + dryad_b2_v6_1 + ${2} + dryad_b2_carry))
    dryad_b2_v1_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_2 + dryad_b2_v6_2 + ${3} + dryad_b2_carry))
    dryad_b2_v1_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_3 + dryad_b2_v6_3 + ${4} + dryad_b2_carry))
    dryad_b2_v1_3=$((dryad_b2_sum & 65535))
    dryad_b2_v12_0=$((dryad_b2_v12_0 ^ dryad_b2_v1_0))
    dryad_b2_v12_1=$((dryad_b2_v12_1 ^ dryad_b2_v1_1))
    dryad_b2_v12_2=$((dryad_b2_v12_2 ^ dryad_b2_v1_2))
    dryad_b2_v12_3=$((dryad_b2_v12_3 ^ dryad_b2_v1_3))
    dryad_b2_r0=$dryad_b2_v12_0
    dryad_b2_r1=$dryad_b2_v12_1
    dryad_b2_r2=$dryad_b2_v12_2
    dryad_b2_r3=$dryad_b2_v12_3
    dryad_b2_v12_0=$dryad_b2_r2
    dryad_b2_v12_1=$dryad_b2_r3
    dryad_b2_v12_2=$dryad_b2_r0
    dryad_b2_v12_3=$dryad_b2_r1
    dryad_b2_sum=$((dryad_b2_v11_0 + dryad_b2_v12_0))
    dryad_b2_v11_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_1 + dryad_b2_v12_1 + dryad_b2_carry))
    dryad_b2_v11_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_2 + dryad_b2_v12_2 + dryad_b2_carry))
    dryad_b2_v11_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_3 + dryad_b2_v12_3 + dryad_b2_carry))
    dryad_b2_v11_3=$((dryad_b2_sum & 65535))
    dryad_b2_v6_0=$((dryad_b2_v6_0 ^ dryad_b2_v11_0))
    dryad_b2_v6_1=$((dryad_b2_v6_1 ^ dryad_b2_v11_1))
    dryad_b2_v6_2=$((dryad_b2_v6_2 ^ dryad_b2_v11_2))
    dryad_b2_v6_3=$((dryad_b2_v6_3 ^ dryad_b2_v11_3))
    dryad_b2_r0=$dryad_b2_v6_0
    dryad_b2_r1=$dryad_b2_v6_1
    dryad_b2_r2=$dryad_b2_v6_2
    dryad_b2_r3=$dryad_b2_v6_3
    dryad_b2_v6_0=$(((dryad_b2_r1 >> 8) | ((dryad_b2_r2 & 255) << 8)))
    dryad_b2_v6_1=$(((dryad_b2_r2 >> 8) | ((dryad_b2_r3 & 255) << 8)))
    dryad_b2_v6_2=$(((dryad_b2_r3 >> 8) | ((dryad_b2_r0 & 255) << 8)))
    dryad_b2_v6_3=$(((dryad_b2_r0 >> 8) | ((dryad_b2_r1 & 255) << 8)))
    dryad_b2_sum=$((dryad_b2_v1_0 + dryad_b2_v6_0 + ${5}))
    dryad_b2_v1_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_1 + dryad_b2_v6_1 + ${6} + dryad_b2_carry))
    dryad_b2_v1_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_2 + dryad_b2_v6_2 + ${7} + dryad_b2_carry))
    dryad_b2_v1_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v1_3 + dryad_b2_v6_3 + ${8} + dryad_b2_carry))
    dryad_b2_v1_3=$((dryad_b2_sum & 65535))
    dryad_b2_v12_0=$((dryad_b2_v12_0 ^ dryad_b2_v1_0))
    dryad_b2_v12_1=$((dryad_b2_v12_1 ^ dryad_b2_v1_1))
    dryad_b2_v12_2=$((dryad_b2_v12_2 ^ dryad_b2_v1_2))
    dryad_b2_v12_3=$((dryad_b2_v12_3 ^ dryad_b2_v1_3))
    dryad_b2_r0=$dryad_b2_v12_0
    dryad_b2_r1=$dryad_b2_v12_1
    dryad_b2_r2=$dryad_b2_v12_2
    dryad_b2_r3=$dryad_b2_v12_3
    dryad_b2_v12_0=$dryad_b2_r1
    dryad_b2_v12_1=$dryad_b2_r2
    dryad_b2_v12_2=$dryad_b2_r3
    dryad_b2_v12_3=$dryad_b2_r0
    dryad_b2_sum=$((dryad_b2_v11_0 + dryad_b2_v12_0))
    dryad_b2_v11_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_1 + dryad_b2_v12_1 + dryad_b2_carry))
    dryad_b2_v11_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_2 + dryad_b2_v12_2 + dryad_b2_carry))
    dryad_b2_v11_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v11_3 + dryad_b2_v12_3 + dryad_b2_carry))
    dryad_b2_v11_3=$((dryad_b2_sum & 65535))
    dryad_b2_v6_0=$((dryad_b2_v6_0 ^ dryad_b2_v11_0))
    dryad_b2_v6_1=$((dryad_b2_v6_1 ^ dryad_b2_v11_1))
    dryad_b2_v6_2=$((dryad_b2_v6_2 ^ dryad_b2_v11_2))
    dryad_b2_v6_3=$((dryad_b2_v6_3 ^ dryad_b2_v11_3))
    dryad_b2_r0=$dryad_b2_v6_0
    dryad_b2_r1=$dryad_b2_v6_1
    dryad_b2_r2=$dryad_b2_v6_2
    dryad_b2_r3=$dryad_b2_v6_3
    dryad_b2_v6_0=$((((dryad_b2_r0 << 1) & 65535) | (dryad_b2_r3 >> 15)))
    dryad_b2_v6_1=$((((dryad_b2_r1 << 1) & 65535) | (dryad_b2_r0 >> 15)))
    dryad_b2_v6_2=$((((dryad_b2_r2 << 1) & 65535) | (dryad_b2_r1 >> 15)))
    dryad_b2_v6_3=$((((dryad_b2_r3 << 1) & 65535) | (dryad_b2_r2 >> 15)))
}

dryad_b2_G_2_7_8_13 () {
    dryad_b2_sum=$((dryad_b2_v2_0 + dryad_b2_v7_0 + ${1}))
    dryad_b2_v2_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_1 + dryad_b2_v7_1 + ${2} + dryad_b2_carry))
    dryad_b2_v2_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_2 + dryad_b2_v7_2 + ${3} + dryad_b2_carry))
    dryad_b2_v2_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_3 + dryad_b2_v7_3 + ${4} + dryad_b2_carry))
    dryad_b2_v2_3=$((dryad_b2_sum & 65535))
    dryad_b2_v13_0=$((dryad_b2_v13_0 ^ dryad_b2_v2_0))
    dryad_b2_v13_1=$((dryad_b2_v13_1 ^ dryad_b2_v2_1))
    dryad_b2_v13_2=$((dryad_b2_v13_2 ^ dryad_b2_v2_2))
    dryad_b2_v13_3=$((dryad_b2_v13_3 ^ dryad_b2_v2_3))
    dryad_b2_r0=$dryad_b2_v13_0
    dryad_b2_r1=$dryad_b2_v13_1
    dryad_b2_r2=$dryad_b2_v13_2
    dryad_b2_r3=$dryad_b2_v13_3
    dryad_b2_v13_0=$dryad_b2_r2
    dryad_b2_v13_1=$dryad_b2_r3
    dryad_b2_v13_2=$dryad_b2_r0
    dryad_b2_v13_3=$dryad_b2_r1
    dryad_b2_sum=$((dryad_b2_v8_0 + dryad_b2_v13_0))
    dryad_b2_v8_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_1 + dryad_b2_v13_1 + dryad_b2_carry))
    dryad_b2_v8_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_2 + dryad_b2_v13_2 + dryad_b2_carry))
    dryad_b2_v8_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_3 + dryad_b2_v13_3 + dryad_b2_carry))
    dryad_b2_v8_3=$((dryad_b2_sum & 65535))
    dryad_b2_v7_0=$((dryad_b2_v7_0 ^ dryad_b2_v8_0))
    dryad_b2_v7_1=$((dryad_b2_v7_1 ^ dryad_b2_v8_1))
    dryad_b2_v7_2=$((dryad_b2_v7_2 ^ dryad_b2_v8_2))
    dryad_b2_v7_3=$((dryad_b2_v7_3 ^ dryad_b2_v8_3))
    dryad_b2_r0=$dryad_b2_v7_0
    dryad_b2_r1=$dryad_b2_v7_1
    dryad_b2_r2=$dryad_b2_v7_2
    dryad_b2_r3=$dryad_b2_v7_3
    dryad_b2_v7_0=$(((dryad_b2_r1 >> 8) | ((dryad_b2_r2 & 255) << 8)))
    dryad_b2_v7_1=$(((dryad_b2_r2 >> 8) | ((dryad_b2_r3 & 255) << 8)))
    dryad_b2_v7_2=$(((dryad_b2_r3 >> 8) | ((dryad_b2_r0 & 255) << 8)))
    dryad_b2_v7_3=$(((dryad_b2_r0 >> 8) | ((dryad_b2_r1 & 255) << 8)))
    dryad_b2_sum=$((dryad_b2_v2_0 + dryad_b2_v7_0 + ${5}))
    dryad_b2_v2_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_1 + dryad_b2_v7_1 + ${6} + dryad_b2_carry))
    dryad_b2_v2_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_2 + dryad_b2_v7_2 + ${7} + dryad_b2_carry))
    dryad_b2_v2_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v2_3 + dryad_b2_v7_3 + ${8} + dryad_b2_carry))
    dryad_b2_v2_3=$((dryad_b2_sum & 65535))
    dryad_b2_v13_0=$((dryad_b2_v13_0 ^ dryad_b2_v2_0))
    dryad_b2_v13_1=$((dryad_b2_v13_1 ^ dryad_b2_v2_1))
    dryad_b2_v13_2=$((dryad_b2_v13_2 ^ dryad_b2_v2_2))
    dryad_b2_v13_3=$((dryad_b2_v13_3 ^ dryad_b2_v2_3))
    dryad_b2_r0=$dryad_b2_v13_0
    dryad_b2_r1=$dryad_b2_v13_1
    dryad_b2_r2=$dryad_b2_v13_2
    dryad_b2_r3=$dryad_b2_v13_3
    dryad_b2_v13_0=$dryad_b2_r1
    dryad_b2_v13_1=$dryad_b2_r2
    dryad_b2_v13_2=$dryad_b2_r3
    dryad_b2_v13_3=$dryad_b2_r0
    dryad_b2_sum=$((dryad_b2_v8_0 + dryad_b2_v13_0))
    dryad_b2_v8_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_1 + dryad_b2_v13_1 + dryad_b2_carry))
    dryad_b2_v8_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_2 + dryad_b2_v13_2 + dryad_b2_carry))
    dryad_b2_v8_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v8_3 + dryad_b2_v13_3 + dryad_b2_carry))
    dryad_b2_v8_3=$((dryad_b2_sum & 65535))
    dryad_b2_v7_0=$((dryad_b2_v7_0 ^ dryad_b2_v8_0))
    dryad_b2_v7_1=$((dryad_b2_v7_1 ^ dryad_b2_v8_1))
    dryad_b2_v7_2=$((dryad_b2_v7_2 ^ dryad_b2_v8_2))
    dryad_b2_v7_3=$((dryad_b2_v7_3 ^ dryad_b2_v8_3))
    dryad_b2_r0=$dryad_b2_v7_0
    dryad_b2_r1=$dryad_b2_v7_1
    dryad_b2_r2=$dryad_b2_v7_2
    dryad_b2_r3=$dryad_b2_v7_3
    dryad_b2_v7_0=$((((dryad_b2_r0 << 1) & 65535) | (dryad_b2_r3 >> 15)))
    dryad_b2_v7_1=$((((dryad_b2_r1 << 1) & 65535) | (dryad_b2_r0 >> 15)))
    dryad_b2_v7_2=$((((dryad_b2_r2 << 1) & 65535) | (dryad_b2_r1 >> 15)))
    dryad_b2_v7_3=$((((dryad_b2_r3 << 1) & 65535) | (dryad_b2_r2 >> 15)))
}

dryad_b2_G_3_4_9_14 () {
    dryad_b2_sum=$((dryad_b2_v3_0 + dryad_b2_v4_0 + ${1}))
    dryad_b2_v3_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_1 + dryad_b2_v4_1 + ${2} + dryad_b2_carry))
    dryad_b2_v3_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_2 + dryad_b2_v4_2 + ${3} + dryad_b2_carry))
    dryad_b2_v3_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_3 + dryad_b2_v4_3 + ${4} + dryad_b2_carry))
    dryad_b2_v3_3=$((dryad_b2_sum & 65535))
    dryad_b2_v14_0=$((dryad_b2_v14_0 ^ dryad_b2_v3_0))
    dryad_b2_v14_1=$((dryad_b2_v14_1 ^ dryad_b2_v3_1))
    dryad_b2_v14_2=$((dryad_b2_v14_2 ^ dryad_b2_v3_2))
    dryad_b2_v14_3=$((dryad_b2_v14_3 ^ dryad_b2_v3_3))
    dryad_b2_r0=$dryad_b2_v14_0
    dryad_b2_r1=$dryad_b2_v14_1
    dryad_b2_r2=$dryad_b2_v14_2
    dryad_b2_r3=$dryad_b2_v14_3
    dryad_b2_v14_0=$dryad_b2_r2
    dryad_b2_v14_1=$dryad_b2_r3
    dryad_b2_v14_2=$dryad_b2_r0
    dryad_b2_v14_3=$dryad_b2_r1
    dryad_b2_sum=$((dryad_b2_v9_0 + dryad_b2_v14_0))
    dryad_b2_v9_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_1 + dryad_b2_v14_1 + dryad_b2_carry))
    dryad_b2_v9_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_2 + dryad_b2_v14_2 + dryad_b2_carry))
    dryad_b2_v9_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_3 + dryad_b2_v14_3 + dryad_b2_carry))
    dryad_b2_v9_3=$((dryad_b2_sum & 65535))
    dryad_b2_v4_0=$((dryad_b2_v4_0 ^ dryad_b2_v9_0))
    dryad_b2_v4_1=$((dryad_b2_v4_1 ^ dryad_b2_v9_1))
    dryad_b2_v4_2=$((dryad_b2_v4_2 ^ dryad_b2_v9_2))
    dryad_b2_v4_3=$((dryad_b2_v4_3 ^ dryad_b2_v9_3))
    dryad_b2_r0=$dryad_b2_v4_0
    dryad_b2_r1=$dryad_b2_v4_1
    dryad_b2_r2=$dryad_b2_v4_2
    dryad_b2_r3=$dryad_b2_v4_3
    dryad_b2_v4_0=$(((dryad_b2_r1 >> 8) | ((dryad_b2_r2 & 255) << 8)))
    dryad_b2_v4_1=$(((dryad_b2_r2 >> 8) | ((dryad_b2_r3 & 255) << 8)))
    dryad_b2_v4_2=$(((dryad_b2_r3 >> 8) | ((dryad_b2_r0 & 255) << 8)))
    dryad_b2_v4_3=$(((dryad_b2_r0 >> 8) | ((dryad_b2_r1 & 255) << 8)))
    dryad_b2_sum=$((dryad_b2_v3_0 + dryad_b2_v4_0 + ${5}))
    dryad_b2_v3_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_1 + dryad_b2_v4_1 + ${6} + dryad_b2_carry))
    dryad_b2_v3_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_2 + dryad_b2_v4_2 + ${7} + dryad_b2_carry))
    dryad_b2_v3_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v3_3 + dryad_b2_v4_3 + ${8} + dryad_b2_carry))
    dryad_b2_v3_3=$((dryad_b2_sum & 65535))
    dryad_b2_v14_0=$((dryad_b2_v14_0 ^ dryad_b2_v3_0))
    dryad_b2_v14_1=$((dryad_b2_v14_1 ^ dryad_b2_v3_1))
    dryad_b2_v14_2=$((dryad_b2_v14_2 ^ dryad_b2_v3_2))
    dryad_b2_v14_3=$((dryad_b2_v14_3 ^ dryad_b2_v3_3))
    dryad_b2_r0=$dryad_b2_v14_0
    dryad_b2_r1=$dryad_b2_v14_1
    dryad_b2_r2=$dryad_b2_v14_2
    dryad_b2_r3=$dryad_b2_v14_3
    dryad_b2_v14_0=$dryad_b2_r1
    dryad_b2_v14_1=$dryad_b2_r2
    dryad_b2_v14_2=$dryad_b2_r3
    dryad_b2_v14_3=$dryad_b2_r0
    dryad_b2_sum=$((dryad_b2_v9_0 + dryad_b2_v14_0))
    dryad_b2_v9_0=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_1 + dryad_b2_v14_1 + dryad_b2_carry))
    dryad_b2_v9_1=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_2 + dryad_b2_v14_2 + dryad_b2_carry))
    dryad_b2_v9_2=$((dryad_b2_sum & 65535))
    dryad_b2_carry=$((dryad_b2_sum >> 16))
    dryad_b2_sum=$((dryad_b2_v9_3 + dryad_b2_v14_3 + dryad_b2_carry))
    dryad_b2_v9_3=$((dryad_b2_sum & 65535))
    dryad_b2_v4_0=$((dryad_b2_v4_0 ^ dryad_b2_v9_0))
    dryad_b2_v4_1=$((dryad_b2_v4_1 ^ dryad_b2_v9_1))
    dryad_b2_v4_2=$((dryad_b2_v4_2 ^ dryad_b2_v9_2))
    dryad_b2_v4_3=$((dryad_b2_v4_3 ^ dryad_b2_v9_3))
    dryad_b2_r0=$dryad_b2_v4_0
    dryad_b2_r1=$dryad_b2_v4_1
    dryad_b2_r2=$dryad_b2_v4_2
    dryad_b2_r3=$dryad_b2_v4_3
    dryad_b2_v4_0=$((((dryad_b2_r0 << 1) & 65535) | (dryad_b2_r3 >> 15)))
    dryad_b2_v4_1=$((((dryad_b2_r1 << 1) & 65535) | (dryad_b2_r0 >> 15)))
    dryad_b2_v4_2=$((((dryad_b2_r2 << 1) & 65535) | (dryad_b2_r1 >> 15)))
    dryad_b2_v4_3=$((((dryad_b2_r3 << 1) & 65535) | (dryad_b2_r2 >> 15)))
}

dryad_b2_compress_shell () {
    dryad_b2_final=$1
    dryad_b2_v0_0=$dryad_b2_h0_0
    dryad_b2_v0_1=$dryad_b2_h0_1
    dryad_b2_v0_2=$dryad_b2_h0_2
    dryad_b2_v0_3=$dryad_b2_h0_3
    dryad_b2_v1_0=$dryad_b2_h1_0
    dryad_b2_v1_1=$dryad_b2_h1_1
    dryad_b2_v1_2=$dryad_b2_h1_2
    dryad_b2_v1_3=$dryad_b2_h1_3
    dryad_b2_v2_0=$dryad_b2_h2_0
    dryad_b2_v2_1=$dryad_b2_h2_1
    dryad_b2_v2_2=$dryad_b2_h2_2
    dryad_b2_v2_3=$dryad_b2_h2_3
    dryad_b2_v3_0=$dryad_b2_h3_0
    dryad_b2_v3_1=$dryad_b2_h3_1
    dryad_b2_v3_2=$dryad_b2_h3_2
    dryad_b2_v3_3=$dryad_b2_h3_3
    dryad_b2_v4_0=$dryad_b2_h4_0
    dryad_b2_v4_1=$dryad_b2_h4_1
    dryad_b2_v4_2=$dryad_b2_h4_2
    dryad_b2_v4_3=$dryad_b2_h4_3
    dryad_b2_v5_0=$dryad_b2_h5_0
    dryad_b2_v5_1=$dryad_b2_h5_1
    dryad_b2_v5_2=$dryad_b2_h5_2
    dryad_b2_v5_3=$dryad_b2_h5_3
    dryad_b2_v6_0=$dryad_b2_h6_0
    dryad_b2_v6_1=$dryad_b2_h6_1
    dryad_b2_v6_2=$dryad_b2_h6_2
    dryad_b2_v6_3=$dryad_b2_h6_3
    dryad_b2_v7_0=$dryad_b2_h7_0
    dryad_b2_v7_1=$dryad_b2_h7_1
    dryad_b2_v7_2=$dryad_b2_h7_2
    dryad_b2_v7_3=$dryad_b2_h7_3
    dryad_b2_v8_0=$dryad_b2_iv0_0
    dryad_b2_v8_1=$dryad_b2_iv0_1
    dryad_b2_v8_2=$dryad_b2_iv0_2
    dryad_b2_v8_3=$dryad_b2_iv0_3
    dryad_b2_v9_0=$dryad_b2_iv1_0
    dryad_b2_v9_1=$dryad_b2_iv1_1
    dryad_b2_v9_2=$dryad_b2_iv1_2
    dryad_b2_v9_3=$dryad_b2_iv1_3
    dryad_b2_v10_0=$dryad_b2_iv2_0
    dryad_b2_v10_1=$dryad_b2_iv2_1
    dryad_b2_v10_2=$dryad_b2_iv2_2
    dryad_b2_v10_3=$dryad_b2_iv2_3
    dryad_b2_v11_0=$dryad_b2_iv3_0
    dryad_b2_v11_1=$dryad_b2_iv3_1
    dryad_b2_v11_2=$dryad_b2_iv3_2
    dryad_b2_v11_3=$dryad_b2_iv3_3
    dryad_b2_v12_0=$dryad_b2_iv4_0
    dryad_b2_v12_1=$dryad_b2_iv4_1
    dryad_b2_v12_2=$dryad_b2_iv4_2
    dryad_b2_v12_3=$dryad_b2_iv4_3
    dryad_b2_v13_0=$dryad_b2_iv5_0
    dryad_b2_v13_1=$dryad_b2_iv5_1
    dryad_b2_v13_2=$dryad_b2_iv5_2
    dryad_b2_v13_3=$dryad_b2_iv5_3
    dryad_b2_v14_0=$dryad_b2_iv6_0
    dryad_b2_v14_1=$dryad_b2_iv6_1
    dryad_b2_v14_2=$dryad_b2_iv6_2
    dryad_b2_v14_3=$dryad_b2_iv6_3
    dryad_b2_v15_0=$dryad_b2_iv7_0
    dryad_b2_v15_1=$dryad_b2_iv7_1
    dryad_b2_v15_2=$dryad_b2_iv7_2
    dryad_b2_v15_3=$dryad_b2_iv7_3
    dryad_b2_v12_0=$((dryad_b2_v12_0 ^ dryad_b2_t0))
    dryad_b2_v12_1=$((dryad_b2_v12_1 ^ dryad_b2_t1))
    dryad_b2_v12_2=$((dryad_b2_v12_2 ^ dryad_b2_t2))
    dryad_b2_v12_3=$((dryad_b2_v12_3 ^ dryad_b2_t3))
    if [ "$dryad_b2_final" = 1 ]; then
        dryad_b2_v14_0=$((dryad_b2_v14_0 ^ 65535))
        dryad_b2_v14_1=$((dryad_b2_v14_1 ^ 65535))
        dryad_b2_v14_2=$((dryad_b2_v14_2 ^ 65535))
        dryad_b2_v14_3=$((dryad_b2_v14_3 ^ 65535))
    fi
    dryad_b2_G_0_4_8_12 "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3" "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3" "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3" "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3" "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3" "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3" "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3" "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3" "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3" "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3" "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3" "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3" "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3" "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3" "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3" "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3" "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3" "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3" "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3" "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3" "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3" "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3" "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3" "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3" "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3" "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3" "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3" "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3" "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3" "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3" "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3" "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3" "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3" "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3" "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3" "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3" "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3" "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3" "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3" "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3" "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3" "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3" "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3" "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3" "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3" "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3" "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3" "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3" "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3" "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3" "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3" "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3" "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3" "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3" "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3" "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3" "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3" "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3" "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3" "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3" "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3" "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3" "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3" "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3" "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3" "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3" "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3" "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3" "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3" "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3" "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3" "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3" "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3" "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3" "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3" "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3" "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3" "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3" "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3" "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3" "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3" "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3" "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3" "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3" "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3" "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3" "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3" "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3" "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3"
    dryad_b2_G_0_4_8_12 "$dryad_b2_m14_0" "$dryad_b2_m14_1" "$dryad_b2_m14_2" "$dryad_b2_m14_3" "$dryad_b2_m10_0" "$dryad_b2_m10_1" "$dryad_b2_m10_2" "$dryad_b2_m10_3"
    dryad_b2_G_1_5_9_13 "$dryad_b2_m4_0" "$dryad_b2_m4_1" "$dryad_b2_m4_2" "$dryad_b2_m4_3" "$dryad_b2_m8_0" "$dryad_b2_m8_1" "$dryad_b2_m8_2" "$dryad_b2_m8_3"
    dryad_b2_G_2_6_10_14 "$dryad_b2_m9_0" "$dryad_b2_m9_1" "$dryad_b2_m9_2" "$dryad_b2_m9_3" "$dryad_b2_m15_0" "$dryad_b2_m15_1" "$dryad_b2_m15_2" "$dryad_b2_m15_3"
    dryad_b2_G_3_7_11_15 "$dryad_b2_m13_0" "$dryad_b2_m13_1" "$dryad_b2_m13_2" "$dryad_b2_m13_3" "$dryad_b2_m6_0" "$dryad_b2_m6_1" "$dryad_b2_m6_2" "$dryad_b2_m6_3"
    dryad_b2_G_0_5_10_15 "$dryad_b2_m1_0" "$dryad_b2_m1_1" "$dryad_b2_m1_2" "$dryad_b2_m1_3" "$dryad_b2_m12_0" "$dryad_b2_m12_1" "$dryad_b2_m12_2" "$dryad_b2_m12_3"
    dryad_b2_G_1_6_11_12 "$dryad_b2_m0_0" "$dryad_b2_m0_1" "$dryad_b2_m0_2" "$dryad_b2_m0_3" "$dryad_b2_m2_0" "$dryad_b2_m2_1" "$dryad_b2_m2_2" "$dryad_b2_m2_3"
    dryad_b2_G_2_7_8_13 "$dryad_b2_m11_0" "$dryad_b2_m11_1" "$dryad_b2_m11_2" "$dryad_b2_m11_3" "$dryad_b2_m7_0" "$dryad_b2_m7_1" "$dryad_b2_m7_2" "$dryad_b2_m7_3"
    dryad_b2_G_3_4_9_14 "$dryad_b2_m5_0" "$dryad_b2_m5_1" "$dryad_b2_m5_2" "$dryad_b2_m5_3" "$dryad_b2_m3_0" "$dryad_b2_m3_1" "$dryad_b2_m3_2" "$dryad_b2_m3_3"
    dryad_b2_h0_0=$((dryad_b2_h0_0 ^ dryad_b2_v0_0 ^ dryad_b2_v8_0))
    dryad_b2_h0_1=$((dryad_b2_h0_1 ^ dryad_b2_v0_1 ^ dryad_b2_v8_1))
    dryad_b2_h0_2=$((dryad_b2_h0_2 ^ dryad_b2_v0_2 ^ dryad_b2_v8_2))
    dryad_b2_h0_3=$((dryad_b2_h0_3 ^ dryad_b2_v0_3 ^ dryad_b2_v8_3))
    dryad_b2_h1_0=$((dryad_b2_h1_0 ^ dryad_b2_v1_0 ^ dryad_b2_v9_0))
    dryad_b2_h1_1=$((dryad_b2_h1_1 ^ dryad_b2_v1_1 ^ dryad_b2_v9_1))
    dryad_b2_h1_2=$((dryad_b2_h1_2 ^ dryad_b2_v1_2 ^ dryad_b2_v9_2))
    dryad_b2_h1_3=$((dryad_b2_h1_3 ^ dryad_b2_v1_3 ^ dryad_b2_v9_3))
    dryad_b2_h2_0=$((dryad_b2_h2_0 ^ dryad_b2_v2_0 ^ dryad_b2_v10_0))
    dryad_b2_h2_1=$((dryad_b2_h2_1 ^ dryad_b2_v2_1 ^ dryad_b2_v10_1))
    dryad_b2_h2_2=$((dryad_b2_h2_2 ^ dryad_b2_v2_2 ^ dryad_b2_v10_2))
    dryad_b2_h2_3=$((dryad_b2_h2_3 ^ dryad_b2_v2_3 ^ dryad_b2_v10_3))
    dryad_b2_h3_0=$((dryad_b2_h3_0 ^ dryad_b2_v3_0 ^ dryad_b2_v11_0))
    dryad_b2_h3_1=$((dryad_b2_h3_1 ^ dryad_b2_v3_1 ^ dryad_b2_v11_1))
    dryad_b2_h3_2=$((dryad_b2_h3_2 ^ dryad_b2_v3_2 ^ dryad_b2_v11_2))
    dryad_b2_h3_3=$((dryad_b2_h3_3 ^ dryad_b2_v3_3 ^ dryad_b2_v11_3))
    dryad_b2_h4_0=$((dryad_b2_h4_0 ^ dryad_b2_v4_0 ^ dryad_b2_v12_0))
    dryad_b2_h4_1=$((dryad_b2_h4_1 ^ dryad_b2_v4_1 ^ dryad_b2_v12_1))
    dryad_b2_h4_2=$((dryad_b2_h4_2 ^ dryad_b2_v4_2 ^ dryad_b2_v12_2))
    dryad_b2_h4_3=$((dryad_b2_h4_3 ^ dryad_b2_v4_3 ^ dryad_b2_v12_3))
    dryad_b2_h5_0=$((dryad_b2_h5_0 ^ dryad_b2_v5_0 ^ dryad_b2_v13_0))
    dryad_b2_h5_1=$((dryad_b2_h5_1 ^ dryad_b2_v5_1 ^ dryad_b2_v13_1))
    dryad_b2_h5_2=$((dryad_b2_h5_2 ^ dryad_b2_v5_2 ^ dryad_b2_v13_2))
    dryad_b2_h5_3=$((dryad_b2_h5_3 ^ dryad_b2_v5_3 ^ dryad_b2_v13_3))
    dryad_b2_h6_0=$((dryad_b2_h6_0 ^ dryad_b2_v6_0 ^ dryad_b2_v14_0))
    dryad_b2_h6_1=$((dryad_b2_h6_1 ^ dryad_b2_v6_1 ^ dryad_b2_v14_1))
    dryad_b2_h6_2=$((dryad_b2_h6_2 ^ dryad_b2_v6_2 ^ dryad_b2_v14_2))
    dryad_b2_h6_3=$((dryad_b2_h6_3 ^ dryad_b2_v6_3 ^ dryad_b2_v14_3))
    dryad_b2_h7_0=$((dryad_b2_h7_0 ^ dryad_b2_v7_0 ^ dryad_b2_v15_0))
    dryad_b2_h7_1=$((dryad_b2_h7_1 ^ dryad_b2_v7_1 ^ dryad_b2_v15_1))
    dryad_b2_h7_2=$((dryad_b2_h7_2 ^ dryad_b2_v7_2 ^ dryad_b2_v15_2))
    dryad_b2_h7_3=$((dryad_b2_h7_3 ^ dryad_b2_v7_3 ^ dryad_b2_v15_3))
}

dryad_b2_hex_nibble_shell_load () {
    case $1 in
        0 ) dyd_ret0=0 ;; 1 ) dyd_ret0=1 ;; 2 ) dyd_ret0=2 ;; 3 ) dyd_ret0=3 ;;
        4 ) dyd_ret0=4 ;; 5 ) dyd_ret0=5 ;; 6 ) dyd_ret0=6 ;; 7 ) dyd_ret0=7 ;;
        8 ) dyd_ret0=8 ;; 9 ) dyd_ret0=9 ;; 10 ) dyd_ret0=a ;; 11 ) dyd_ret0=b ;;
        12 ) dyd_ret0=c ;; 13 ) dyd_ret0=d ;; 14 ) dyd_ret0=e ;; 15 ) dyd_ret0=f ;;
        * ) dryad_die "invalid hex nibble: $1" ;;
    esac
}

dryad_b2_hex_byte_shell_append () {
    dryad_b2_hex_byte=$1
    dryad_b2_hex_nibble_shell_load $((dryad_b2_hex_byte >> 4))
    dryad_b2_hex_output=$dryad_b2_hex_output$dyd_ret0
    dryad_b2_hex_nibble_shell_load $((dryad_b2_hex_byte & 15))
    dryad_b2_hex_output=$dryad_b2_hex_output$dyd_ret0
}

dryad_b2_output_hex_shell_load () {
    dryad_b2_hex_output=
    dryad_b2_hex_byte_shell_append $((dryad_b2_h0_0 & 255))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h0_0 >> 8))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h0_1 & 255))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h0_1 >> 8))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h0_2 & 255))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h0_2 >> 8))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h0_3 & 255))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h0_3 >> 8))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h1_0 & 255))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h1_0 >> 8))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h1_1 & 255))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h1_1 >> 8))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h1_2 & 255))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h1_2 >> 8))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h1_3 & 255))
    dryad_b2_hex_byte_shell_append $((dryad_b2_h1_3 >> 8))
    dyd_ret0=$dryad_b2_hex_output
}

dryad_b2_base32_char_shell_append () {
    dryad_base32_char_load "$1"
    dryad_b2_base32_output=$dryad_b2_base32_output$dyd_ret0
}

dryad_b2_output_base32_shell_load () {
    dryad_b2_d0=$((dryad_b2_h0_0 & 255))
    dryad_b2_d1=$((dryad_b2_h0_0 >> 8))
    dryad_b2_d2=$((dryad_b2_h0_1 & 255))
    dryad_b2_d3=$((dryad_b2_h0_1 >> 8))
    dryad_b2_d4=$((dryad_b2_h0_2 & 255))
    dryad_b2_d5=$((dryad_b2_h0_2 >> 8))
    dryad_b2_d6=$((dryad_b2_h0_3 & 255))
    dryad_b2_d7=$((dryad_b2_h0_3 >> 8))
    dryad_b2_d8=$((dryad_b2_h1_0 & 255))
    dryad_b2_d9=$((dryad_b2_h1_0 >> 8))
    dryad_b2_d10=$((dryad_b2_h1_1 & 255))
    dryad_b2_d11=$((dryad_b2_h1_1 >> 8))
    dryad_b2_d12=$((dryad_b2_h1_2 & 255))
    dryad_b2_d13=$((dryad_b2_h1_2 >> 8))
    dryad_b2_d14=$((dryad_b2_h1_3 & 255))
    dryad_b2_d15=$((dryad_b2_h1_3 >> 8))
    dryad_b2_base32_output=
    dryad_b2_base32_char_shell_append $((dryad_b2_d0 >> 3))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d0 & 7) << 2) | (dryad_b2_d1 >> 6)))
    dryad_b2_base32_char_shell_append $(((dryad_b2_d1 >> 1) & 31))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d1 & 1) << 4) | (dryad_b2_d2 >> 4)))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d2 & 15) << 1) | (dryad_b2_d3 >> 7)))
    dryad_b2_base32_char_shell_append $(((dryad_b2_d3 >> 2) & 31))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d3 & 3) << 3) | (dryad_b2_d4 >> 5)))
    dryad_b2_base32_char_shell_append $((dryad_b2_d4 & 31))
    dryad_b2_base32_char_shell_append $((dryad_b2_d5 >> 3))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d5 & 7) << 2) | (dryad_b2_d6 >> 6)))
    dryad_b2_base32_char_shell_append $(((dryad_b2_d6 >> 1) & 31))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d6 & 1) << 4) | (dryad_b2_d7 >> 4)))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d7 & 15) << 1) | (dryad_b2_d8 >> 7)))
    dryad_b2_base32_char_shell_append $(((dryad_b2_d8 >> 2) & 31))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d8 & 3) << 3) | (dryad_b2_d9 >> 5)))
    dryad_b2_base32_char_shell_append $((dryad_b2_d9 & 31))
    dryad_b2_base32_char_shell_append $((dryad_b2_d10 >> 3))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d10 & 7) << 2) | (dryad_b2_d11 >> 6)))
    dryad_b2_base32_char_shell_append $(((dryad_b2_d11 >> 1) & 31))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d11 & 1) << 4) | (dryad_b2_d12 >> 4)))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d12 & 15) << 1) | (dryad_b2_d13 >> 7)))
    dryad_b2_base32_char_shell_append $(((dryad_b2_d13 >> 2) & 31))
    dryad_b2_base32_char_shell_append $((((dryad_b2_d13 & 3) << 3) | (dryad_b2_d14 >> 5)))
    dryad_b2_base32_char_shell_append $((dryad_b2_d14 & 31))
    dryad_b2_base32_char_shell_append $((dryad_b2_d15 >> 3))
    dryad_b2_base32_char_shell_append $(((dryad_b2_d15 & 7) << 2))
    dyd_ret0=$dryad_b2_base32_output
}

dryad_b2_hash_file_shell () {
    dryad_b2_file=$1
    dryad_b2_format=${2:-hex}
    dryad_b2_od_tmp=${TMPDIR:-/tmp}/dryad-sh-hash-od.$$
    rm -f "$dryad_b2_od_tmp"
    if ! od -An -v -tu1 -w128 "$dryad_b2_file" > "$dryad_b2_od_tmp"; then
        rm -f "$dryad_b2_od_tmp"
        return 1
    fi
    dryad_b2_reset_shell
    dryad_b2_have_block=0
    dryad_b2_pending_line=
    while IFS= read -r dryad_b2_line; do
        [ -n "$dryad_b2_line" ] || continue
        if [ "$dryad_b2_have_block" = 1 ]; then
            set -- $dryad_b2_pending_line
            dryad_b2_load_block_shell "$@"
            dryad_b2_add_counter_shell "$dryad_b2_block_len"
            dryad_b2_compress_shell 0
        fi
        dryad_b2_pending_line=$dryad_b2_line
        dryad_b2_have_block=1
    done < "$dryad_b2_od_tmp"
    rm -f "$dryad_b2_od_tmp"
    if [ "$dryad_b2_have_block" = 1 ]; then
        set -- $dryad_b2_pending_line
        dryad_b2_load_block_shell "$@"
    else
        dryad_b2_load_block_shell
    fi
    dryad_b2_add_counter_shell "$dryad_b2_block_len"
    dryad_b2_compress_shell 1
    case $dryad_b2_format in
        base32 ) dryad_b2_output_base32_shell_load ;;
        hex ) dryad_b2_output_hex_shell_load ;;
        * ) dryad_die "unsupported shell hash format: $dryad_b2_format" ;;
    esac
}

dryad_blake2b_128_file_hex_shell_load () {
    dryad_b2_hash_file_shell "$1" hex
}

dryad_blake2b_128_file_base32_shell_load () {
    dryad_b2_hash_file_shell "$1" base32
}

dryad_blake2b_128_file_prefixed_base32_shell_load () {
    dryad_b2_prefixed_file=$1
    dryad_b2_od_tmp=${TMPDIR:-/tmp}/dryad-sh-hash-od.$$
    rm -f "$dryad_b2_od_tmp"
    if ! od -An -v -tu1 -w128 "$dryad_b2_prefixed_file" > "$dryad_b2_od_tmp"; then
        rm -f "$dryad_b2_od_tmp"
        return 1
    fi
    dryad_b2_reset_shell
    dryad_b2_have_block=0
    dryad_b2_loaded_block=0
    dryad_b2_pending_line=
    while IFS= read -r dryad_b2_line; do
        [ -n "$dryad_b2_line" ] || continue
        if [ "$dryad_b2_have_block" = 1 ]; then
            set -- $dryad_b2_pending_line
            if [ "$dryad_b2_loaded_block" = 0 ]; then
                dryad_b2_load_initial_prefixed_block_shell "$@"
            else
                dryad_b2_load_carried_prefixed_block_shell "$@"
            fi
            dryad_b2_add_counter_shell "$dryad_b2_block_len"
            dryad_b2_compress_shell 0
            dryad_b2_loaded_block=1
        fi
        dryad_b2_pending_line=$dryad_b2_line
        dryad_b2_have_block=1
    done < "$dryad_b2_od_tmp"
    rm -f "$dryad_b2_od_tmp"
    if [ "$dryad_b2_have_block" = 1 ]; then
        set -- $dryad_b2_pending_line
        if [ "$dryad_b2_loaded_block" = 0 ]; then
            dryad_b2_load_initial_prefixed_block_shell "$@"
        else
            dryad_b2_load_carried_prefixed_block_shell "$@"
        fi
    else
        dryad_b2_load_initial_prefixed_block_shell
    fi
    if [ "$dryad_b2_carry_len" -gt 0 ]; then
        dryad_b2_add_counter_shell "$dryad_b2_block_len"
        dryad_b2_compress_shell 0
        dryad_b2_load_final_carry_block_shell
    fi
    dryad_b2_add_counter_shell "$dryad_b2_block_len"
    dryad_b2_compress_shell 1
    dryad_b2_output_base32_shell_load
}
