---
name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - draft-*

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Bootstrap
        working-directory: ${{ github.workspace }}
        run: ./utils/nix-shell/run.sh ./utils/bootstrap-build.sh

      - name: Build Garden
        working-directory: ${{ github.workspace }}
        run: ./utils/nix-shell/run.sh ./utils/dryad-garden-build.sh
        continue-on-error: true  # Allow this step to fail without stopping the job

      - name: Run Tests
        if: success()  # Only run if all previous steps succeeded
        working-directory: ${{ github.workspace }}
        run: ./utils/nix-shell/run.sh ./utils/dryad-run-tests.sh
        continue-on-error: true  # Allow this step to fail without stopping the job

      - name: Save Logs
        if: always()  # This ensures it runs even if the previous step failed
        uses: actions/upload-artifact@v4
        with:
          name: logs--${{ matrix.os }}
          path: logs
